/* ============================================================
 * XTJ 英语学习 — 常用词库 (2000+ 词, 涵盖 CET-4/6)
 * 格式: { en: '单词', cn: '中文释义', phonetic: '音标(可选)' }
 * ============================================================ */

(function() {
  'use strict';

  var WORDS = [
    // ===== CET-4 高频核心词 (A) =====
    { en: 'a', cn: '一(个); 任何一个' },
    { en: 'abandon', cn: '放弃; 抛弃' },
    { en: 'ability', cn: '能力; 才能' },
    { en: 'able', cn: '能够; 有能力的' },
    { en: 'abnormal', cn: '反常的; 不正常的' },
    { en: 'aboard', cn: '在船(车)上; 上船' },
    { en: 'about', cn: '关于; 大约' },
    { en: 'above', cn: '在...上面; 以上' },
    { en: 'abroad', cn: '到(在)国外' },
    { en: 'absence', cn: '缺席; 不在场' },
    { en: 'absent', cn: '缺席的; 不在的' },
    { en: 'absolute', cn: '绝对的; 完全的' },
    { en: 'absolutely', cn: '完全地; 绝对地' },
    { en: 'absorb', cn: '吸收; 使全神贯注' },
    { en: 'abstract', cn: '抽象的; 摘要' },
    { en: 'absurd', cn: '荒唐的; 荒谬的' },
    { en: 'abundant', cn: '丰富的; 充裕的' },
    { en: 'abuse', cn: '滥用; 虐待' },
    { en: 'academic', cn: '学术的; 学院的' },
    { en: 'academy', cn: '学院; 研究院' },
    { en: 'accelerate', cn: '加速; 促进' },
    { en: 'accent', cn: '口音; 重音' },
    { en: 'accept', cn: '接受; 同意' },
    { en: 'acceptable', cn: '可接受的; 合意的' },
    { en: 'acceptance', cn: '接受; 承认' },
    { en: 'access', cn: '通道; 访问' },
    { en: 'accessible', cn: '可进入的; 可使用的' },
    { en: 'accident', cn: '事故; 意外的事' },
    { en: 'accidental', cn: '偶然的; 意外的' },
    { en: 'accommodation', cn: '住处; 膳宿' },
    { en: 'accompany', cn: '陪伴; 伴随' },
    { en: 'accomplish', cn: '完成; 实现' },
    { en: 'accomplishment', cn: '成就; 造诣' },
    { en: 'according', cn: '按照; 根据' },
    { en: 'account', cn: '账户; 描述' },
    { en: 'accountant', cn: '会计; 会计师' },
    { en: 'accumulate', cn: '积累; 累积' },
    { en: 'accuracy', cn: '准确性; 精确度' },
    { en: 'accurate', cn: '精确的; 准确的' },
    { en: 'accuse', cn: '控告; 指责' },
    { en: 'achieve', cn: '取得; 实现' },
    { en: 'achievement', cn: '成就; 成绩' },
    { en: 'acid', cn: '酸; 酸的' },
    { en: 'acknowledge', cn: '承认; 答谢' },
    { en: 'acquaintance', cn: '熟人; 相识' },
    { en: 'acquire', cn: '获得; 习得' },
    { en: 'acre', cn: '英亩' },
    { en: 'across', cn: '横过; 在...对面' },
    { en: 'act', cn: '行动; 表演' },
    { en: 'action', cn: '行动' },
    { en: 'active', cn: '积极的; 活跃的' },
    { en: 'activity', cn: '活动' },
    { en: 'actor', cn: '男演员' },
    { en: 'actress', cn: '女演员' },
    { en: 'actual', cn: '实际的; 真实的' },
    { en: 'actually', cn: '实际上; 事实上' },
    { en: 'ad', cn: '广告' },
    { en: 'adapt', cn: '使适应; 改编' },
    { en: 'add', cn: '添加; 增加' },
    { en: 'addition', cn: '加; 加法' },
    { en: 'additional', cn: '附加的; 额外的' },
    { en: 'address', cn: '地址; 演说' },
    { en: 'adequate', cn: '足够的; 适当的' },
    { en: 'adjective', cn: '形容词' },
    { en: 'adjust', cn: '调整; 调节' },
    { en: 'administration', cn: '管理; 行政' },
    { en: 'admirable', cn: '令人钦佩的' },
    { en: 'admire', cn: '钦佩; 羡慕' },
    { en: 'admission', cn: '承认; 准许进入' },
    { en: 'admit', cn: '承认; 接纳' },
    { en: 'adolescent', cn: '青少年' },
    { en: 'adopt', cn: '收养; 采用' },
    { en: 'adore', cn: '爱慕; 崇拜' },
    { en: 'adult', cn: '成年人' },
    { en: 'advance', cn: '前进; 进步' },
    { en: 'advanced', cn: '高级的; 先进的' },
    { en: 'advantage', cn: '优点; 好处' },
    { en: 'adventure', cn: '冒险; 奇遇' },
    { en: 'adverb', cn: '副词' },
    { en: 'advertise', cn: '为...做广告' },
    { en: 'advertisement', cn: '广告' },
    { en: 'advice', cn: '忠告; 建议' },
    { en: 'advise', cn: '劝告; 建议' },
    { en: 'advocate', cn: '拥护; 提倡' },
    { en: 'affair', cn: '事; 事情' },
    { en: 'affect', cn: '影响' },
    { en: 'affection', cn: '爱; 爱慕' },
    { en: 'afford', cn: '买得起; 负担得起' },
    { en: 'afraid', cn: '害怕的; 担心的' },
    { en: 'Africa', cn: '非洲' },
    { en: 'African', cn: '非洲的' },
    { en: 'after', cn: '在...以后' },
    { en: 'afternoon', cn: '下午' },
    { en: 'afterwards', cn: '后来; 以后' },
    { en: 'again', cn: '再; 又' },
    { en: 'against', cn: '对着; 反对' },
    { en: 'age', cn: '年龄; 年龄段' },
    { en: 'aged', cn: '年老的' },
    { en: 'agency', cn: '代理; 代理处' },
    { en: 'agent', cn: '代理人; 代理商' },
    { en: 'aggressive', cn: '侵略的; 好斗的' },
    { en: 'ago', cn: '以前' },
    { en: 'agree', cn: '同意; 赞成' },
    { en: 'agreement', cn: '同意; 一致' },
    { en: 'agricultural', cn: '农业的' },
    { en: 'agriculture', cn: '农业; 农艺' },
    { en: 'ahead', cn: '在前; 向前' },
    { en: 'aid', cn: '援助; 帮助' },
    { en: 'AIDS', cn: '艾滋病' },
    { en: 'aim', cn: '目的; 目标' },
    { en: 'air', cn: '空气; 大气' },
    { en: 'aircraft', cn: '飞机' },
    { en: 'airline', cn: '航空公司' },
    { en: 'airmail', cn: '航空邮件' },
    { en: 'airplane', cn: '飞机' },
    { en: 'airport', cn: '机场; 航空站' },
    { en: 'airspace', cn: '领空' },
    { en: 'alarm', cn: '警报; 惊恐' },
    { en: 'album', cn: '相册; 集邮簿' },
    { en: 'alcohol', cn: '酒精; 酒' },
    { en: 'alcoholic', cn: '酒精的' },
    { en: 'alike', cn: '相同的; 一样的' },
    { en: 'alive', cn: '活着的; 存在的' },
    { en: 'all', cn: '全部的; 全部' },
    { en: 'allergic', cn: '过敏的' },
    { en: 'alley', cn: '小巷; 胡同' },
    { en: 'alliance', cn: '联盟; 同盟' },
    { en: 'allow', cn: '允许; 准许' },
    { en: 'allowance', cn: '津贴; 补贴' },
    { en: 'ally', cn: '同盟者; 伙伴' },
    { en: 'almost', cn: '几乎; 差不多' },
    { en: 'alone', cn: '单独的; 独自的' },
    { en: 'along', cn: '向前; 沿着' },
    { en: 'alongside', cn: '在...旁边; 沿着' },
    { en: 'aloud', cn: '出声地; 大声地' },
    { en: 'alphabet', cn: '字母表' },
    { en: 'already', cn: '已经' },
    { en: 'also', cn: '也' },
    { en: 'alternative', cn: '可选择的事物' },
    { en: 'although', cn: '虽然; 尽管' },
    { en: 'altitude', cn: '高度; 海拔' },
    { en: 'altogether', cn: '完全; 总共' },
    { en: 'aluminum', cn: '铝' },
    { en: 'always', cn: '总是; 一直' },
    { en: 'a.m.', cn: '上午' },
    { en: 'amaze', cn: '使吃惊' },
    { en: 'amazing', cn: '惊人的; 了不起的' },
    { en: 'ambassador', cn: '大使' },
    { en: 'ambiguous', cn: '含糊不清的' },
    { en: 'ambition', cn: '雄心; 野心' },
    { en: 'ambitious', cn: '有抱负的; 野心勃勃的' },
    { en: 'ambulance', cn: '救护车' },
    { en: 'amid', cn: '在...之中' },
    { en: 'among', cn: '在...中间' },
    { en: 'amount', cn: '数量; 总数' },
    { en: 'amuse', cn: '使发笑; 娱乐' },
    { en: 'amusement', cn: '消遣; 娱乐' },
    { en: 'an', cn: '一(个); 任何一个' },
    { en: 'analyse', cn: '分析; 解析' },
    { en: 'analysis', cn: '分析' },
    { en: 'analyst', cn: '分析家; 化验员' },
    { en: 'analyze', cn: '分析; 解析' },
    { en: 'ancestor', cn: '祖宗; 祖先' },
    { en: 'anchor', cn: '锚' },
    { en: 'ancient', cn: '古代的; 古老的' },
    { en: 'and', cn: '和; 并; 又; 就' },
    { en: 'anecdote', cn: '轶事; 趣闻' },
    { en: 'angel', cn: '天使' },
    { en: 'anger', cn: '怒; 愤怒' },
    { en: 'angle', cn: '角; 角度' },
    { en: 'angry', cn: '愤怒的; 生气的' },
    { en: 'animal', cn: '动物; 牲畜' },
    { en: 'animation', cn: '动画片; 生气' },
    { en: 'ankle', cn: '踝(关节)' },
    { en: 'anniversary', cn: '周年纪念日' },
    { en: 'announce', cn: '宣布; 宣告' },
    { en: 'announcement', cn: '宣告; 通告' },
    { en: 'annoy', cn: '使烦恼; 打扰' },
    { en: 'annual', cn: '每年的; 一年一次的' },
    { en: 'another', cn: '再一个; 另一个' },
    { en: 'answer', cn: '回答; 答复' },
    { en: 'ant', cn: '蚂蚁' },
    { en: 'antarctic', cn: '南极的' },
    { en: 'antibiotic', cn: '抗生素' },
    { en: 'anticipate', cn: '预期; 预料' },
    { en: 'anxiety', cn: '担心; 焦虑' },
    { en: 'anxious', cn: '忧虑的; 焦急的' },
    { en: 'any', cn: '任何; 任何一个' },
    { en: 'anybody', cn: '任何人' },
    { en: 'anyhow', cn: '不管怎样' },
    { en: 'anyone', cn: '任何人' },
    { en: 'anything', cn: '任何东西' },
    { en: 'anyway', cn: '不管怎样' },
    { en: 'anywhere', cn: '任何地方' },
    { en: 'apart', cn: '相隔; 分开' },
    { en: 'apartment', cn: '公寓; 住房' },
    { en: 'apologize', cn: '道歉; 谢罪' },
    { en: 'apology', cn: '道歉; 歉意' },
    { en: 'apparent', cn: '显然的; 表面上的' },
    { en: 'apparently', cn: '显然地' },
    { en: 'appeal', cn: '呼吁; 恳求' },
    { en: 'appear', cn: '出现; 呈现' },
    { en: 'appearance', cn: '出现; 露面' },
    { en: 'appendix', cn: '附录; 阑尾' },
    { en: 'appetite', cn: '食欲; 胃口' },
    { en: 'applaud', cn: '鼓掌; 赞成' },
    { en: 'applause', cn: '鼓掌; 喝彩' },
    { en: 'apple', cn: '苹果' },
    { en: 'appliance', cn: '用具; 器具' },
    { en: 'applicant', cn: '申请人' },
    { en: 'application', cn: '申请' },
    { en: 'apply', cn: '申请; 适用' },
    { en: 'appoint', cn: '任命; 委派' },
    { en: 'appointment', cn: '约会' },
    { en: 'appreciate', cn: '欣赏; 感激' },
    { en: 'appreciation', cn: '欣赏; 感激' },
    { en: 'approach', cn: '接近; 方法' },
    { en: 'appropriate', cn: '适当的' },
    { en: 'approval', cn: '赞成; 同意' },
    { en: 'approve', cn: '赞成; 同意' },
    { en: 'approximate', cn: '大约的; 近似的' },
    { en: 'April', cn: '4 月' },
    { en: 'apron', cn: '围裙' },
    { en: 'Arab', cn: '阿拉伯人' },
    { en: 'Arabic', cn: '阿拉伯语' },
    { en: 'arbitrary', cn: '随意的; 任意的' },
    { en: 'arch', cn: '拱; 弓形结构' },
    { en: 'architect', cn: '建筑师' },
    { en: 'architecture', cn: '建筑学' },
    { en: 'Arctic', cn: '北极的' },
    { en: 'are', cn: '是' },
    { en: 'area', cn: '面积; 地区' },
    { en: 'arena', cn: '竞技场; 舞台' },
    { en: 'argue', cn: '争论; 辩论' },
    { en: 'argument', cn: '争论; 辩论' },
    { en: 'arise', cn: '出现; 发生' },
    { en: 'arithmetic', cn: '算术' },
    { en: 'arm', cn: '臂; 武器' },
    { en: 'armchair', cn: '扶手椅' },
    { en: 'army', cn: '军队' },
    { en: 'around', cn: '在...周围; 到处' },
    { en: 'arouse', cn: '唤起; 激起' },
    { en: 'arrange', cn: '安排; 布置' },
    { en: 'arrangement', cn: '安排' },
    { en: 'arrest', cn: '逮捕; 拘留' },
    { en: 'arrival', cn: '到来; 到达' },
    { en: 'arrive', cn: '到达; 达到' },
    { en: 'arrow', cn: '箭; 箭头' },
    { en: 'art', cn: '艺术; 美术' },
    { en: 'article', cn: '文章; 条款' },
    { en: 'artificial', cn: '人工的; 人造的' },
    { en: 'artist', cn: '艺术家' },
    { en: 'artistic', cn: '艺术的' },
    { en: 'as', cn: '像...一样; 当...时候' },
    { en: 'ash', cn: '灰; 灰末' },
    { en: 'ashamed', cn: '惭愧; 羞耻' },
    { en: 'Asia', cn: '亚洲' },
    { en: 'Asian', cn: '亚洲的' },
    { en: 'aside', cn: '在旁边; 到一边' },
    { en: 'ask', cn: '问; 询问' },
    { en: 'asleep', cn: '睡着的' },
    { en: 'aspect', cn: '方面; 外观' },
    { en: 'aspirin', cn: '阿司匹林' },
    { en: 'assemble', cn: '集合; 装配' },
    { en: 'assembly', cn: '集合; 装配' },
    { en: 'assess', cn: '评估; 评价' },
    { en: 'assessment', cn: '评估; 评价' },
    { en: 'asset', cn: '资产; 财产' },
    { en: 'assign', cn: '分配; 指派' },
    { en: 'assignment', cn: '任务; 作业' },
    { en: 'assist', cn: '帮助; 协助' },
    { en: 'assistance', cn: '援助; 帮助' },
    { en: 'assistant', cn: '助手; 助理' },
    { en: 'associate', cn: '联合; 联想' },
    { en: 'association', cn: '协会; 联想' },
    { en: 'assume', cn: '假定; 承担' },
    { en: 'assumption', cn: '假定; 假设' },
    { en: 'assure', cn: '使确信; 保证' },
    { en: 'astonish', cn: '使惊讶' },
    { en: 'astronaut', cn: '宇航员; 太空人' },
    { en: 'astronomer', cn: '天文学家' },
    { en: 'astronomy', cn: '天文学' },
    { en: 'at', cn: '在...里; 在...时' },
    { en: 'athlete', cn: '运动员' },
    { en: 'athletic', cn: '运动的; 运动员的' },
    { en: 'Atlantic', cn: '大西洋' },
    { en: 'atmosphere', cn: '大气; 气氛' },
    { en: 'atom', cn: '原子' },
    { en: 'atomic', cn: '原子的' },
    { en: 'attach', cn: '系上; 贴上' },
    { en: 'attachment', cn: '附件; 附属物' },
    { en: 'attack', cn: '攻击; 进攻' },
    { en: 'attain', cn: '达到; 获得' },
    { en: 'attempt', cn: '尝试; 企图' },
    { en: 'attend', cn: '出席; 参加' },
    { en: 'attendance', cn: '出席; 参加' },
    { en: 'attendant', cn: '服务员; 侍者' },
    { en: 'attention', cn: '注意; 关心' },
    { en: 'attentively', cn: '注意地' },
    { en: 'attitude', cn: '态度; 看法' },
    { en: 'attorney', cn: '律师' },
    { en: 'attract', cn: '吸引; 引起注意' },
    { en: 'attraction', cn: '吸引; 吸引力' },
    { en: 'attractive', cn: '有吸引力的' },
    { en: 'auction', cn: '拍卖' },
    { en: 'audience', cn: '观众; 听众' },
    { en: 'audio', cn: '声音的; 音频的' },
    { en: 'August', cn: '8 月' },
    { en: 'aunt', cn: '姨; 姑母; 舅母' },
    { en: 'Australia', cn: '澳洲; 澳大利亚' },
    { en: 'Australian', cn: '澳洲的; 澳大利亚的' },
    { en: 'author', cn: '作者; 作家' },
    { en: 'authority', cn: '权力; 权威' },
    { en: 'autobiography', cn: '自传' },
    { en: 'autograph', cn: '亲笔签名' },
    { en: 'automatic', cn: '自动的' },
    { en: 'automobile', cn: '汽车' },
    { en: 'autonomous', cn: '自治的; 自主的' },
    { en: 'autumn', cn: '秋天; 秋季' },
    { en: 'available', cn: '可用的; 可得到的' },
    { en: 'avenue', cn: '大街; 林荫道' },
    { en: 'average', cn: '平均数; 平均的' },
    { en: 'avoid', cn: '避免; 躲开' },
    { en: 'awake', cn: '醒着的; 唤醒' },
    { en: 'award', cn: '奖品; 判给' },
    { en: 'aware', cn: '意识到的; 知道的' },
    { en: 'awareness', cn: '意识; 了解' },
    { en: 'away', cn: '离开; 远离' },
    { en: 'awesome', cn: '令人敬畏的; 极好的' },
    { en: 'awful', cn: '糟糕的; 可怕的' },
    { en: 'awkward', cn: '笨拙的; 尴尬的' }
  ];

  // 暴露全局词典
  window.ENGLISH_WORD_DICT = WORDS;
})();
