'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const src=fs.readFileSync('js/admin/admin.js','utf8');const server=fs.readFileSync('render-api/server.js','utf8');
function between(s,start,end){const a=s.indexOf(start),b=s.indexOf(end,a+start.length);assert.ok(a>=0&&b>a);return s.slice(a,b);}
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
function node(){return {appendChild(){},style:{},value:'',disabled:false,textContent:'',innerHTML:'',classList:{remove(){},add(){}}};}
function context(extra={}){const nodes=new Map();return vm.createContext({window:{},console,AbortController,DOMException,setTimeout,clearTimeout,clearInterval,Map,Set,URL,document:{createElement:()=>node(),getElementById(id){if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);},querySelector(){return node();},removeEventListener(){}},...extra});}
function detailContext(){const pending=new Map(),paints=[];const c=context({_adminSessionGeneration:0,_adminDetailGeneration:0,_adminDetailAbortController:null,allUsers:[],allLoginEvents:[],allBehaviorEvents:[],allSecurityAlerts:[],bansData:[],mutesData:[],getUserActivityStats:()=>({posts:0,likes:0,comments:0}),getUserStateFlags:()=>({}),buildUserTagMarkup:()=>'',mergeAdminUserInfo:(a,b)=>({...a,...b}),safeJsStr:s=>String(s??''),escapeHtml:s=>String(s??''),formatTime:s=>String(s??''),adminFormatLocation:l=>l?.text||'',getAdminUserEffectiveRegTime:()=>'',getLoginRecordModelText:()=>'',toAdminTimeMs:s=>new Date(s||0).getTime(),buildUserSummaryMarkup:()=>'',showToast:()=>{},bindAdminGpsHistory:()=>{},bindAdminFlashLimits:()=>{},showModal:(title,html)=>paints.push(html),apiCall:async(_method,path)=>{if(path.startsWith('/admin/user-location-history'))return {items:[]};const name=new URL('https://local'+path).searchParams.get('user_name');const d=deferred();pending.set(name,d);return d.promise;}});vm.runInContext(between(src,'window.closeAdminDetailModal = function()','function showModal'),c);vm.runInContext(between(src,'window.showUserDetailModal = async function(userName)','// 管理员手动重新解析 GPS 地址'),c);return {c,pending,paints};}
test('user detail commits B and discards A when responses arrive in reverse order',async()=>{const {c,pending,paints}=detailContext();const a=c.window.showUserDetailModal('A'),b=c.window.showUserDetailModal('B');pending.get('B').resolve({info:{},login_events:[]});await b;assert.match(paints.at(-1),/<h2[^>]*>B<\/h2>/);pending.get('A').resolve({info:{},login_events:[]});await a;assert.match(paints.at(-1),/<h2[^>]*>B<\/h2>/);assert.deepEqual(Array.from(c.allUsers,u=>u.name),['B']);});
test('closing detail before response prevents repaint and cached private data writes',async()=>{const {c,pending,paints}=detailContext();const a=c.window.showUserDetailModal('A');const count=paints.length;c.window.closeAdminDetailModal();pending.get('A').resolve({info:{email:'private@example.invalid'}});await a;assert.equal(paints.length,count);assert.equal(c.allUsers.length,0);});
test('historical missing IP geography remains unrecorded rather than current location',async()=>{const {c,pending,paints}=detailContext();const a=c.window.showUserDetailModal('A');pending.get('A').resolve({info:{last_ip:'2.2.2.2',last_ip_location:{text:'Current region'},last_location:{address:'GPS address'}},login_events:[{user_name:'A',created_at:'2026-01-01',content:JSON.stringify({ip:'1.1.1.1',login_at:'2026-01-01'})}]});await a;const html=paints.at(-1),history=html.slice(html.indexOf('最近登录记录'));assert.match(history,/1\.1\.1\.1/);assert.match(history,/未记录/);assert.doesNotMatch(history,/Current region|GPS address/);});
test('admin Cookie login succeeds when the optional ordinary user token is unavailable',async()=>{let initialized=0,cleared=0;const c=context({API_BASE:'https://local',ADMIN:null,ADMIN_LOGIN_TIMEOUT_MS:1000,_adminLogoutPromise:null,_adminSessionGeneration:0,fetch:async()=>({ok:true,status:200,json:async()=>({ok:true,user_token:null})}),initAdminClient:async()=>{initialized++;},setToken:()=>assert.fail('no null token may be stored'),clearToken:()=>{cleared++;},isFetchAbortError:()=>false});c.document.getElementById('loginName').value='xxz';c.document.getElementById('loginPw').value='test-only';vm.runInContext(between(src,'window.doAdminLogin = async function()','window.confirmLogout = function()'),c);await c.window.doAdminLogin();assert.equal(initialized,1);assert.equal(c.ADMIN,'xxz');assert.equal(cleared,1);});
test('admin API deadline also aborts a stalled response body',async()=>{const c=context({API_BASE:'https://local',_adminSessionGeneration:0,refreshUserAccessToken:async()=>'',saveSession:()=>{},clearSession:()=>{},getToken:()=>'',fetch:async(_url,opts)=>({status:200,ok:true,json:()=>new Promise((_resolve,reject)=>opts.signal.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError')),{once:true}))})});vm.runInContext(between(src,'async function apiCall(method, path, body, options)','function showToast'),c);await assert.rejects(c.apiCall('GET','/admin/users',null,{timeoutMs:15}),e=>e.name==='AbortError');});
function userLogoutContext(){let handler;const revoked=[],deleted=[],cookies=[];const c=context({PHOTO_COOKIE:require('../render-api/photo-access').PHOTO_COOKIE,POST_MEDIA_COOKIE:require('../render-api/photo-access').POST_MEDIA_COOKIE,app:{post(_path,...parts){handler=parts.at(-1);}},rateLimit:()=>()=>{},ADMIN_USERNAME:'xxz',waitForRevocationState:async()=>true,verifySignedToken:t=>t==='admin'?{user:'xxz'}:null,isTokenRevoked:()=>false,_getTokenFromRequest:r=>r.headers.authorization?.slice(7)||'',verifyUserAccessToken:t=>t==='accessA'?{user_name:'xxz',jti:'a',exp:10000}:t==='accessB'?{user_name:'B',jti:'b',exp:10000}:null,verifyUserRefreshToken:t=>({user_name:t==='refreshB'?'B':'xxz',jti:t}),persistRevokedToken:async t=>{revoked.push(t);return true;},REFRESH_TOKEN_MARKER:'__refresh_token__',supabase:{from(){return {delete(){const filters={};return {eq(k,v){filters[k]=v;if(k==='media_url'){deleted.push(filters);return Promise.resolve({error:null});}return this;}};}};}}});vm.runInContext(between(server,"app.post('/api/user/logout'",'// 验证 token 是否有效'),c);return {handler,revoked,deleted,cookies,response:{statusCode:200,status(n){this.statusCode=n;return this;},json(body){this.body=body;return this;},clearCookie(name,opts){cookies.push({name,opts});}}};}
test('admin companion logout preserves a different ordinary account Cookie',async()=>{const x=userLogoutContext();await x.handler({headers:{authorization:'Bearer accessA'},body:{admin_companion_logout:true},cookies:{xtj_admin_token:'admin',xtj_user_refresh:'refreshB'}},x.response);assert.equal(x.response.body.preserved_other_session,true);assert.deepEqual(x.revoked,['accessA']);assert.equal(x.deleted.length,0);assert.equal(x.cookies.length,0);});
test('admin companion logout revokes only the same browser refresh and same principal access',async()=>{const x=userLogoutContext();await x.handler({headers:{authorization:'Bearer accessA'},body:{admin_companion_logout:true},cookies:{xtj_admin_token:'admin',xtj_user_refresh:'refreshA'}},x.response);assert.equal(x.response.body.ok,true);assert.equal(x.deleted.length,1);assert.equal(x.deleted[0].media_url,'refreshA');assert.equal(x.cookies[0].opts.path,'/api/user');assert.deepEqual(x.cookies.slice(1).map(c=>[c.name,c.opts.path]),[['xtj_photo_session','/api/photo'],['xtj_post_media_session','/api/post'],['xtj_post_media_session','/api/uploads']]);});
test('admin companion mode rejects calls lacking the real administrator Cookie',async()=>{const x=userLogoutContext();await x.handler({headers:{authorization:'Bearer accessA'},body:{admin_companion_logout:true},cookies:{xtj_user_refresh:'refreshA'}},x.response);assert.equal(x.response.statusCode,401);assert.equal(x.deleted.length,0);assert.equal(x.revoked.length,0);});
test('ordinary token A plus Cookie B cannot revoke or clear B',async()=>{const x=userLogoutContext();await x.handler({headers:{authorization:'Bearer accessA'},body:{},cookies:{xtj_user_refresh:'refreshB'}},x.response);assert.equal(x.response.body.preserved_other_session,true);assert.equal(x.deleted.length,0);assert.equal(x.cookies.length,0);});
test('admin logout clears the browser Cookie even when durable revocation fails',async()=>{let handler;const cookies=[];const c=context({app:{post(_path,...parts){handler=parts.at(-1);}},verifyToken:()=>{},adminTokens:new Map(),verifySignedToken:()=>({exp:1000}),revokedTokens:new Map(),persistRevokedToken:async()=>false,TOKEN_EXPIRY_MS:1000});vm.runInContext(between(server,"app.post('/admin/logout'",'// ===================== 自动过期函数'),c);const res={statusCode:200,clearCookie:n=>cookies.push(n),status(n){this.statusCode=n;return this;},json(b){this.body=b;return this;}};await handler({adminToken:'admin'},res);assert.equal(res.statusCode,503);assert.deepEqual(cookies,['xtj_admin_token']);});
test('MCP opt-in supports explicit local development ports and still rejects nonlocal HTTP',()=>{const text=fs.readFileSync('mcp-servers/xtj-admin/server.js','utf8');const c=context({process:{env:{}}});vm.runInContext(between(text,'function validateApiBase','let API_BASE;'),c);const env={NODE_ENV:'development',XTJ_MCP_ALLOW_LOCALHOST:'true'};for(const origin of ['http://localhost:3000','http://127.0.0.1:4444','http://[::1]:8080'])assert.equal(c.validateApiBase(origin,env),origin);assert.throws(()=>c.validateApiBase('http://example.com:3000',env));assert.throws(()=>c.validateApiBase('http://localhost:3000',{...env,NODE_ENV:'production'}));});

test('admin logout clears sensitive UI immediately and exposes a failed revocation retry',async()=>{
 const pending=deferred(),calls=[];const c=context({API_BASE:'https://local',ADMIN:'xxz',_adminSessionGeneration:0,_adminLogoutPromise:null,_allDataLoadGeneration:0,_allDataAbortController:null,_adminSessionTimer:null,_adminReportPollTimer:null,onlineRefreshTimer:null,sessionTimeoutMonitorStarted:false,adminTabSwitchGeneration:0,allPosts:[{private:true}],allLikes:[],allComments:[],allUsers:[{private:true}],annList:[],allLoginEvents:[],allBehaviorEvents:[],allSecurityAlerts:[],allAuditLogs:[],allErrorLogs:[],reportsData:[],reportsLoading:false,reportsLoadError:'',adminTabDataLoaded:{},adminDataLoadPromises:{},_allDataLoadPromise:null,adminDataLoading:false,stopRegisterAlertPolling:()=>{},getToken:()=>'',clearSession:()=>{},_handleAdminVisibilityChange:()=>{},resetActivityTimer:()=>{},showToast:()=>{},fetch:async(url)=>{calls.push(url);return pending.promise;}});
 c.window.closeAdminDetailModal=()=>{};vm.runInContext(between(src,'window.doAdminLogout = async function()','// 登录表单键盘导航'),c);
 const logout=c.window.doAdminLogout();assert.equal(c.document.getElementById('dashboard').style.display,'none');assert.equal(c.allUsers.length,0);assert.equal(c.ADMIN,null);
 pending.resolve({ok:false,status:503,json:async()=>({error:'temporary failure'})});assert.equal(await logout,false);assert.match(c.document.getElementById('loginErr').textContent,/撤销未确认/);assert.equal(calls.length,1);
});
