'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require('playwright');
const source=fs.readFileSync('js/core-parts/06-chat-and-nav.js','utf8');
function slice(start,end){const a=source.indexOf(start);return source.slice(a,source.indexOf(end,a));}
async function browserPage(){const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||(fs.existsSync('/usr/bin/chromium')?'/usr/bin/chromium':undefined),headless:true,args:['--no-sandbox']});const page=await browser.newPage();await page.route('https://xtj.test/**',route=>route.fulfill({contentType:'text/html',body:'<button id="opener">查看</button><div id="output"></div>'}));await page.goto('https://xtj.test/');return{browser,page};}
test('real DOM Markdown images render with alt; streamed text updates without losing cursor',async()=>{const {browser,page}=await browserPage();try{await page.addScriptTag({content:fs.readFileSync('js/ai-core/markdown-renderer.js','utf8')});await page.addScriptTag({content:fs.readFileSync('js/ai-core/stream-renderer.js','utf8')});const result=await page.evaluate(()=>{const md=XtjAiCore.Markdown,output=document.getElementById('output');output.innerHTML=md.render('![猫](https://xtj.test/cat.png)');const image={count:output.querySelectorAll('img').length,alt:output.querySelector('img')?.alt,links:output.querySelectorAll('a').length};XtjAiCore.Markdown={render:x=>x};const renderer=XtjAiCore.StreamRenderer.create(output);output.replaceChildren();renderer.append('Hello');renderer.flush();renderer.append(' world');renderer.flush();const text=output.textContent,cursor=output.querySelectorAll('.ai-stream-cursor').length;renderer.finish();return{image,text,cursor};});assert.deepEqual(result,{image:{count:1,alt:'猫',links:0},text:'Hello world',cursor:1});}finally{await browser.close();}});
test('flash Escape restores focus; failed receipt locks recipient locally and retry remains account isolated',async()=>{const {browser,page}=await browserPage();try{await page.addStyleTag({content:fs.readFileSync('css/ui-shell.css','utf8')});const helpers=slice('            var _flashViewer=', '            function paintChatFlashQuota()');const open=slice('            window.openChatFlash=async function', "            document.addEventListener('visibilitychange',function(){if(document.hidden&&_flashViewer)");await page.evaluate(({helpers,open})=>{window.currentUser='A';window._authStateEpoch=1;window.dockChatActiveUser='P';window._chatCache={};window._chatRenderSignature={};window.getDockChatCacheKey=p=>p;window.renderDockMessages=()=>{};window.showToast=()=>{};window.calls=[];window.mode='sender';window.failAck=true;window.failImage=false;window.xtjProtectedFetch=async(path,options)=>{window.calls.push({path,owner:options.authOwner,epoch:options.authEpoch});if(path.endsWith('/viewed')){if(window.failAck)throw Error('offline');return new Response(JSON.stringify({ok:true}),{headers:{'content-type':'application/json'}});}if(window.failImage)return new Response('invalid-image',{headers:{'content-type':'image/png','X-Flash-Role':window.mode}});const bytes=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aJ1sAAAAASUVORK5CYII='),c=>c.charCodeAt(0));return new Response(bytes,{headers:{'content-type':'image/png','X-Flash-Role':window.mode}});};window.eval(helpers+'\n'+open);}, {helpers,open});
 await page.focus('#opener');await page.evaluate(()=>openChatFlash('123e4567-e89b-42d3-a456-426614174000'));await page.waitForSelector('#chatFlashViewer.is-sender');assert.equal(await page.evaluate(()=>document.activeElement.className),'flash-close');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'opener');await page.waitForSelector('#chatFlashViewer',{state:'detached'});
 await page.evaluate(()=>{mode='recipient';failImage=true;return openChatFlash('123e4567-e89b-42d3-a456-426614174002');});await page.waitForSelector('#chatFlashViewer',{state:'detached'});assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('xtj_flash_receipts_A')||'{}')['123e4567-e89b-42d3-a456-426614174002']),undefined);
 await page.evaluate(()=>{failImage=false;return openChatFlash('123e4567-e89b-42d3-a456-426614174001');});await page.waitForFunction(()=>JSON.parse(localStorage.getItem('xtj_flash_receipts_A')||'{}')['123e4567-e89b-42d3-a456-426614174001']?.presented===true);await page.keyboard.press('Escape');await page.waitForSelector('#chatFlashViewer',{state:'detached'});const before=await page.evaluate(()=>calls.filter(x=>x.path.endsWith('/open')).length);await page.evaluate(()=>openChatFlash('123e4567-e89b-42d3-a456-426614174001'));assert.equal(await page.evaluate(()=>calls.filter(x=>x.path.endsWith('/open')).length),before);await page.evaluate(()=>{currentUser='B';_authStateEpoch++;});const acknowledgements=await page.evaluate(()=>calls.filter(x=>x.path.endsWith('/viewed')).length);await page.waitForTimeout(1300);assert.equal(await page.evaluate(()=>calls.filter(x=>x.path.endsWith('/viewed')).length),acknowledgements);assert.equal(await page.evaluate(()=>localStorage.getItem('xtj_flash_receipts_B')),null);await page.evaluate(()=>{currentUser='A';_authStateEpoch++;failAck=false;window.dispatchEvent(new Event('online'));});await page.waitForFunction(()=>JSON.parse(localStorage.getItem('xtj_flash_receipts_A'))['123e4567-e89b-42d3-a456-426614174001'].confirmed);assert.equal(await page.evaluate(()=>calls.at(-1).owner),'A');
 }finally{await browser.close();}});
