'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('js/ai-agent.js','utf8');
function runtime(){let owner='alice',epoch=1,refreshes=0,failures=0;const window={currentUser:owner,__xtjGetAuthEpoch:()=>epoch,refreshUserToken:async()=>{refreshes++;return '';},handleProtectedAuthFailure(){failures++;}};const c={window,AI_DEBUG:false,CONFIG_CACHE_TTL:300000,S:{},Date,Promise,console,readUserName:()=>owner,sendOnce:async()=>({ok:false,status:401}),updateAiStatus(){}};vm.createContext(c);const start=source.indexOf('  async function apiRequest('),end=source.indexOf('  function buildUsageLine(',start);vm.runInContext(source.slice(start,end),c);return{c,window,get refreshes(){return refreshes;},get failures(){return failures;},change(value){owner=value;window.currentUser=value;epoch++;}};}
test('guest AI configuration uses entry defaults without protected requests or login cleanup',async()=>{const r=runtime();r.change('');let requests=0;r.c.sendOnce=async()=>{requests++;return{status:401};};assert.equal((await r.c.ensureConfig()).name,'小猫');assert.equal(requests,0);assert.equal(r.refreshes,0);assert.equal(r.failures,0);assert.equal(r.c.S.configFetchedAt,undefined);});
test('guest AI 401 responses cannot refresh a login, clear public posts, or force a login dialog',async()=>{const r=runtime();r.change('');await r.c.apiRequest('GET','/chat/history');assert.equal(r.c.describeError({status:401}),'请先登录后再和小猫聊天');assert.equal(r.refreshes,0);assert.equal(r.failures,0);});
test('an old AI response cannot clear an account after A to B to A replacement',async()=>{const r=runtime();let release;r.c.sendOnce=()=>new Promise(resolve=>release=resolve);const result=r.c.apiRequest('GET','/config');r.change('bob');r.change('alice');release({status:401});assert.equal((await result).error_code,'aborted');assert.equal(r.refreshes,0);assert.equal(r.failures,0);});
test('an identity change during forced refresh cannot clear the replacement login',async()=>{const r=runtime();let release;r.window.refreshUserToken=()=>new Promise(resolve=>release=resolve);const task=r.c.apiRequest('GET','/config');await new Promise(setImmediate);assert.equal(typeof release,'function');r.change('bob');release('old-access');assert.equal((await task).error_code,'aborted');assert.equal(r.failures,0);});
test('authenticated background configuration keeps its background failure handling',async()=>{const r=runtime();const calls=[];r.window.handleProtectedAuthFailure=opts=>calls.push(opts);await r.c.apiRequest('GET','/config',null,{background:true});assert.equal(r.refreshes,1);assert.equal(calls.length,1);assert.equal(calls[0].background,true);});
test('background configuration error descriptions never turn into foreground login prompts',async()=>{const r=runtime();const calls=[];r.window.handleProtectedAuthFailure=opts=>calls.push(opts);await r.c.ensureConfig();assert.ok(calls.length);assert.equal(calls.every(opts=>opts.background),true);});
