'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const responsesContext=require('../render-api/responses-context');
const source=fs.readFileSync('render-api/server.js','utf8');
const start=source.indexOf('async function callDeepSeekViaResponses('),end=source.indexOf('\nasync function ',start+10);
function load(fetch){const c={fetch,AbortController,TextDecoder,Response,setTimeout,clearTimeout,aiTaskPolicy:require('../render-api/ai-task-policy'),responsesContext,console:{log(){},warn(){},error(){}},DEEPSEEK_API_KEY:'test',DEEPSEEK_RESPONSES_URL:'https://test.invalid/responses',DEEPSEEK_RESPONSES_MODEL:'deepseek-flash',DEBUG_PROVIDER:false,DEBUG_PROVIDER_ALWAYS:false,getPreferredDeepSeekModel:x=>x,executeToolCall:async()=>({ok:true}),finalReplyContainsInternalProtocolGlobal:()=>false,looksLikeToolArgsFragment:()=>false,responsesUsageToInternal:()=>({prompt_tokens:1,completion_tokens:1,total_tokens:2})};vm.createContext(c);vm.runInContext(source.slice(start,end)+'\nglobalThis.call=callDeepSeekViaResponses;',c);return c.call;}
function stream(events){return new Response(events.map(e=>'data: '+JSON.stringify(e)+'\n\n').join(''),{headers:{'content-type':'text/event-stream'}});}
const tools=[{type:'function',function:{name:'lookup',parameters:{type:'object'}}}];
for(const streaming of [false,true])test('real Responses tool loop preserves provider reasoning_text, encrypted fields and distinct call IDs ('+streaming+')',async()=>{let requests=0,executed=0,body='';const raw={type:'reasoning',id:'reason-1',content:[{type:'reasoning_text',text:'核对原始来源'}],summary:[],encrypted_content:'opaque-context'};
 const call=load(async(_url,init)=>{const req=JSON.parse(init.body);requests++;assert.equal(req.reasoning.effort,'max');if(requests===1){const fc={type:'function_call',id:'item-search',call_id:'call-search',name:'lookup',arguments:'{"query":"福州"}'};if(!streaming)return new Response(JSON.stringify({output:[raw,fc]}));return stream([{type:'response.output_item.added',output_index:0,item:{type:'reasoning',id:'reason-1',content:[]}},{type:'response.reasoning_text.delta',item_id:'reason-1',output_index:0,content_index:0,delta:'核对原始来源'},{type:'response.output_item.done',output_index:0,item:raw},{type:'response.output_text.delta',delta:'我先核对。'},{type:'response.output_item.added',output_index:1,item:fc},{type:'response.completed',response:{output:[raw,fc]}}]);}
 const reasoning=req.input.find(i=>i.type==='reasoning');assert.deepEqual(reasoning,raw);const fc=req.input.find(i=>i.type==='function_call');assert.equal(fc.id,'item-search');assert.equal(fc.call_id,'call-search');assert.equal(req.input.find(i=>i.type==='function_call_output').call_id,'call-search');return streaming?stream([{type:'response.output_text.delta',delta:'核对完成。'},{type:'response.completed',response:{}}]):new Response(JSON.stringify({output:[{type:'message',role:'assistant',content:[{type:'output_text',text:'核对完成。'}]}]}));});
 const options={tools,thinking_mode:'max',max_tool_rounds:10,tool_executor:async tc=>{executed++;assert.equal(tc.id,'call-search');return{ok:true};}};if(streaming){options.onThinkingChunk=()=>{};options.onContentChunk=x=>body+=x;}const result=await call([{role:'user',content:'核对'}],options);assert.equal(result.content,'核对完成。');assert.equal(requests,2);assert.equal(executed,1);if(streaming)assert.equal(body,'我先核对。\n\n核对完成。');
});
test('reasoning collector restores delta-only content and preserves authoritative completed items',()=>{const c=responsesContext.createReasoningCollector();c.add({type:'reasoning',id:'r',content:[]},0);c.delta({item_id:'r',output_index:0,content_index:0,delta:'第一段'});c.delta({item_id:'r',output_index:0,content_index:0,delta:'第二段'});assert.equal(responsesContext.reasoningText(c.items[0]),'第一段第二段');c.add({type:'reasoning',id:'r',content:[{type:'reasoning_text',text:'完整文本'}],encrypted_content:'opaque'},0);assert.equal(c.items.length,1);assert.equal(responsesContext.reasoningText(c.items[0]),'完整文本');assert.equal(c.items[0].encrypted_content,'opaque');});
test('parallel same-name function argument deltas stay with their output items',async()=>{let requests=0;const args=[];const call=load(async()=>{requests++;if(requests>1)return stream([{type:'response.output_text.delta',delta:'完成'},{type:'response.completed',response:{}}]);return stream([{type:'response.output_item.added',output_index:0,item:{type:'function_call',id:'i1',call_id:'c1',name:'lookup',arguments:''}},{type:'response.output_item.added',output_index:1,item:{type:'function_call',id:'i2',call_id:'c2',name:'lookup',arguments:''}},{type:'response.function_call_arguments.delta',item_id:'i1',output_index:0,delta:'{"query":"甲"}'},{type:'response.function_call_arguments.delta',item_id:'i2',output_index:1,delta:'{"query":"乙"}'},{type:'response.completed',response:{}}]);});await call([{role:'user',content:'两次搜索'}],{tools,thinking_mode:'off',onContentChunk(){},tool_executor:async tc=>{args.push([tc.id,JSON.parse(tc.function.arguments).query]);return{ok:true};}});assert.deepEqual(args,[['c1','甲'],['c2','乙']]);});
