'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {postBrowserFixture,wireAiChat}=require('./helpers/post-browser-fixture');
async function authors(f){let requests=0;await f.page.route('**/api/profile/posts/**',route=>{requests++;const author=decodeURIComponent(new URL(route.request().url()).pathname.split('/').at(-1));return route.fulfill({json:{ok:true,author,posts:f.posts.filter(p=>p.user_name===author),has_more:false,next_cursor:null}})});return()=>requests}
for(const [label,viewport,theme]of [['phone light',{width:390,height:844},'light'],['phone dark',{width:390,height:844},'dark'],['desktop',{width:1280,height:900},'light']])test(label+': author avatar opens real dated posts, full galleries and existing interactions',{timeout:60000},async()=>{
 const f=await postBrowserFixture({viewport,theme,counts:[3,15]});try{const{page}=f,count=await authors(f);const dock=await page.locator('#dockBar').evaluate(e=>[e.offsetWidth,e.offsetHeight,e.querySelectorAll('.dock-tab').length]);
 await page.locator('#feed .avatar[role="button"], #feed .avatar-wrap[role="button"]').first().press('Enter');await page.waitForSelector('#authorPostsList .author-post-row');assert.equal(await page.locator('#authorPostsList .author-post-row').count(),2);assert.equal(count(),1);assert.equal(await page.locator('.author-post-photo-count').textContent(),'+11');assert.ok(await page.locator('#authorPostsCover img').count());assert.equal(await page.locator('.author-post-year').textContent(),'2026');
 assert.equal(await page.locator('#userProfileModal').evaluate(e=>e.scrollWidth<=innerWidth),true);const avatar=await page.locator('#upcAvatar').boundingBox();assert.ok(avatar.width>60&&avatar.width<80);
 await page.locator('.author-post-entry').nth(1).click();await page.waitForFunction(()=>document.querySelectorAll('#postDetailBody .post-media-cell').length===15);assert.equal(await page.locator('#postDetailModal').evaluate(e=>getComputedStyle(e).zIndex), '110');await page.locator('#postDetailBody .post-media-cell').nth(10).click();await page.waitForFunction(()=>window.photoPreviewCurrent?.__xtjMediaIndex===10);await page.evaluate(()=>ppNextPhoto());await page.waitForFunction(()=>window.photoPreviewCurrent?.__xtjMediaIndex===11);await page.evaluate(()=>closePhotoPreview());await page.waitForFunction(()=>!document.getElementById('photoPreviewOverlay').classList.contains('active'));await page.evaluate(()=>closeModal('postDetailModal'));await page.waitForFunction(()=>!document.getElementById('postDetailModal').classList.contains('active'));assert.equal(await page.locator('#authorPostsList .author-post-row').count(),2);
 await page.locator('.author-post-entry').first().click();await page.waitForFunction(()=>document.querySelectorAll('#postDetailBody .post-media-cell').length===3);await page.locator('#postDetailBody .like-btn').click();await page.waitForFunction(()=>document.querySelector('#postDetailBody .like-btn').classList.contains('liked'));await page.evaluate(()=>closeModal('postDetailModal'));await page.waitForFunction(()=>!document.getElementById('postDetailModal').classList.contains('active'));
 assert.deepEqual(await page.locator('#dockBar').evaluate(e=>[e.offsetWidth,e.offsetHeight,e.querySelectorAll('.dock-tab').length]),dock);assert.deepEqual(f.errors,[]);
 }finally{await f.close()}
});
test('author navigation ignores stale responses, retries and loads pages without duplicate posts',{timeout:45000},async()=>{
 const f=await postBrowserFixture({counts:[3,15]});try{let release;const held=new Promise(r=>release=r);let fail=true,n=0;await f.page.route('**/api/profile/posts/**',async route=>{const u=new URL(route.request().url()),author=u.pathname.split('/').at(-1);if(author==='slow'){await held;return route.fulfill({json:{ok:true,author,posts:[{...f.posts[0],user_name:'slow'}]}})}if(fail){return route.fulfill({status:503,json:{ok:false,error:'暂时无法加载'}})}n++;return route.fulfill({json:{ok:true,author,posts:[f.posts[n===1?0:1]],has_more:n===1,next_cursor:n===1?{at:f.posts[0].created_at,id:f.posts[0].id}:null}})});
 await f.page.evaluate(()=>openUserProfile('slow'));await f.page.evaluate(()=>openUserProfile('alice'));await f.page.getByRole('button',{name:'重试',exact:true}).waitFor();fail=false;await f.page.getByRole('button',{name:'重试',exact:true}).click();await f.page.waitForSelector('.author-post-row');await f.page.getByRole('button',{name:'加载更多',exact:true}).click();await f.page.waitForFunction(()=>document.querySelectorAll('.author-post-row').length===2);release();await f.page.waitForTimeout(100);assert.equal(await f.page.locator('#upcName').textContent(),'alice');assert.equal(await f.page.locator('.author-post-row').count(),2);
 await f.page.evaluate(()=>{window.__xtjRemoveAuthorPost(document.querySelector('.author-post-row').dataset.postId)});assert.equal(await f.page.locator('.author-post-row').count(),1);await f.page.evaluate(()=>{currentUser='bob';window.dispatchEvent(new Event('auth-ready'))});await f.page.waitForFunction(()=>!document.getElementById('userProfileModal').classList.contains('active'));assert.equal(await f.page.locator('.author-post-row').count(),0);assert.deepEqual(f.errors,[]);
 }finally{await f.close()}
});
test('post detail remains visible after an animated close and rapid reopen, and retries errors',{timeout:45000},async()=>{
 const f=await postBrowserFixture({counts:[15]});try{const{page}=f;await page.evaluate(()=>{document.documentElement.classList.remove('perf-lite');document.documentElement.setAttribute('data-xtj-motion','full');window.gsap={killTweensOf(){},fromTo(el,from,to){el.style.opacity='1';if(to.onComplete)to.onComplete()},to(el,options){el.style.opacity='0';setTimeout(()=>{if(options.onComplete)options.onComplete()},220)}}});await page.addScriptTag({path:'js/core-animations.js'});
 const id=f.posts[0].id;await page.evaluate(id=>openPostDetail(id),id);await page.waitForFunction(()=>document.querySelectorAll('#postDetailBody .post-media-cell').length===15);await page.evaluate(()=>closeModal('postDetailModal'));await page.evaluate(id=>openPostDetail(id),id);await page.waitForTimeout(350);assert.equal(await page.locator('#postDetailModal').evaluate(e=>e.classList.contains('active')),true);assert.equal(await page.locator('#postDetailModal .modal-box').evaluate(e=>getComputedStyle(e).opacity),'1');assert.equal(await page.locator('#postDetailBody .post-media-cell').count(),15);
 await page.evaluate(()=>closeModal('postDetailModal'));await page.waitForTimeout(400);await page.evaluate(id=>openPostDetail(id),id);await page.waitForFunction(()=>document.querySelectorAll('#postDetailBody .post-media-cell').length===15);assert.equal(await page.locator('#postDetailModal .modal-box').evaluate(e=>getComputedStyle(e).opacity),'1');
 let fail=true;await page.route('**/api/post/detail/**',route=>fail?route.fulfill({status:503,json:{ok:false,message:'图片暂时加载失败'}}):route.fulfill({json:{ok:true,post:f.posts[0],likes:[],comments:[]}}));await page.evaluate(id=>openPostDetail(id),id);await page.getByRole('button',{name:'重新加载',exact:true}).waitFor();fail=false;await page.getByRole('button',{name:'重新加载',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('#postDetailBody .post-media-cell').length===15);assert.deepEqual(f.errors,[]);
 }finally{await f.close()}
});
test('publishing shows the photo wall animation and real transfer progress in the existing button',{timeout:45000},async()=>{
 const f=await postBrowserFixture({counts:[3],realUploads:true});try{const{page}=f;await page.route('**/test-supabase/storage/v1/object/uploads/**',route=>route.continue());await page.locator('#fileInp').setInputFiles([0,1,2].map(i=>({name:'photo-'+i+'.png',mimeType:'image/png',buffer:f.png})));await page.locator('#pubBtn').click();await page.waitForSelector('#pubBtn .post-publish-progress');assert.equal(await page.locator('#pubBtn .pw-garden.is-growing').count(),1);await page.waitForFunction(()=>Number(document.querySelector('#pubBtn [role="progressbar"]').getAttribute('aria-valuenow'))>0);assert.ok(Number(await page.locator('#pubBtn [role="progressbar"]').getAttribute('aria-valuenow'))<100);assert.equal(await page.locator('#pwUploadProgressOverlay').evaluate(e=>e.classList.contains('active')),false);assert.equal(f.storageRequests.length,3);assert.ok(f.storageRequests.every(r=>r.body.includes(f.png)));f.releaseStorageResponses();await page.waitForFunction(()=>!document.getElementById('pubBtn').disabled&&selectedPostMedia.length===0);assert.equal(f.getCreated().attachments.length,3);assert.deepEqual(f.errors,[]);
 }finally{await f.close()}
});
test('AI history preserves real thinking time and compact user message height after reopening',{timeout:45000},async()=>{
 const f=await postBrowserFixture({counts:[3]});try{const{page}=f;await wireAiChat(page);await page.locator('#aiChatMsgInput').fill('你是谁');await page.locator('#aiChatSendBtn').click();await page.waitForFunction(()=>!!window.testStream);await page.evaluate(()=>{testEmit({type:'reasoning_start'});testEmit({type:'reasoning',text:'先理解问题'});testEmit({type:'content',text:'我是小猫。'});testEmit({type:'done',content:'我是小猫。',reasoning:'先理解问题',thinking_mode:'max',thinking_elapsed_ms:9000,saved:true,conversation_id:'test'})});await page.waitForFunction(()=>document.querySelector('.ai-thinking-label')?.textContent==='已思考 9s');const before=await page.locator('.ai-msg.user .ai-msg-bubble').boundingBox();assert.ok(before.height<60,'a one-line user message should not gain empty paragraphs');await page.evaluate(()=>window.__xtjCloseAiChat());await page.evaluate(()=>window.__xtjOpenAiChat());await page.waitForFunction(()=>document.querySelector('.ai-thinking-label')?.textContent==='已思考 9s');assert.deepEqual(f.errors,[]);
 }finally{await f.close()}
});
