'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),express=require('express'),request=require('supertest'),sharp=require('sharp'),crypto=require('node:crypto');
const {createFlashPhotos,seal,unseal,BUCKET}=require('../render-api/flash-photos');
const id=n=>'123e4567-e89b-42d3-a456-'+String(n).padStart(12,'0');
function fixture(options={}){
 const tables={posts:[{id:id(1),user_name:'actor',media_type:'__auth__'}],dm_flash_photos:[],dm_flash_limits:[],dm_flash_settings:[{id:true,free_daily:3,pro_daily:20}]},files=new Map(),calls=[],pro=[],notifications=[];let used=0;
 function query(rows){let filters=[],change=null,cap=Infinity;const q={select(){return q;},eq(k,v){filters.push(r=>r[k]===v);return q;},is(k,v){filters.push(r=>(r[k]??null)===v);return q;},order(){return q;},limit(n){cap=n;return q;},or(value){const match=value.match(/consumed_at\.lte\.([^),]+)/);if(match)filters.push(r=>r.message_id==null||(r.consumed_at!=null&&r.consumed_at<=match[1])||(r.consumed_at==null&&r.expires_at<=new Date().toISOString()));return q;},update(v){change=v;return q;},async upsert(v){rows.push(v);return{data:v};},result(){const found=rows.filter(r=>filters.every(f=>f(r))).slice(0,cap);if(change)found.forEach(r=>Object.assign(r,change));return found;},async maybeSingle(){return{data:q.result()[0]||null};},async single(){return{data:q.result()[0]};},then(a,b){return Promise.resolve({data:q.result()}).then(a,b);}};return q;}
 const supabase={from(n){return query(tables[n]||[]);},storage:{from(n){assert.equal(n,BUCKET);return{async upload(path,bytes,config){calls.push(['upload',path,config]);files.set(path,Buffer.from(bytes));return{data:{path}};},async download(path){calls.push(['download',path]);return options.downloadError?{error:Error('failure')}:{data:new Blob([files.get(path)])};},async remove(paths){calls.push(['remove',...paths]);if(options.removeError)return{error:Error('failure')};paths.forEach(p=>files.delete(p));return{data:paths};},async list(){return{data:[]};}};}},async rpc(n,a){calls.push([n,a]);if(n==='dm_flash_quota')return{data:{ok:true,limit:3,used,remaining:Math.max(0,3-used)}};if(n==='dm_flash_send'){
  let existing=tables.dm_flash_photos.find(r=>r.client_id===a.p_client);if(existing)return{data:{ok:true,idempotent:true,message:tables.posts.find(r=>r.id===existing.message_id)}};
  if(used>=3)return{data:{ok:false,code:'flash_quota_exceeded'}};const message={id:crypto.randomUUID(),user_name:a.p_actor,media_url:a.p_peer,content:JSON.stringify({text:'[闪图 3 秒]',flash:{id:a.p_id,state:'ready',duration_ms:3000}})};tables.posts.push(message);tables.dm_flash_photos.push({id:a.p_id,message_id:message.id,client_id:a.p_client,sender_account:id(1),recipient_name:a.p_peer,storage_path:a.p_path,key_material:a.p_key,iv:a.p_iv,tag:a.p_tag,mime:a.p_mime,consumed_at:null});used++;
  return options.commitResponseLost?{error:Error('response lost')}:{data:{ok:true,message}};
 }if(n==='dm_flash_claim'){const r=tables.dm_flash_photos.find(r=>r.message_id===a.p_message);if(!r||!['actor','peer'].includes(a.p_actor))return{data:{ok:false,code:'not_found'}};if(!r.key_material)return{data:{ok:false,code:'flash_expired'}};const data={ok:true,id:r.id,path:r.storage_path,key:r.key_material,iv:r.iv,tag:r.tag,mime:r.mime};r.key_material=null;r.consumed_at=new Date().toISOString();return{data};}if(n==='dm_flash_configure')return{data:true};throw Error('unexpected RPC');}};
 const app=express();app.use(express.json());const feature=createFlashPhotos({express,supabase,sharp,authenticateUser(req,res,next){if(!req.get('authorization'))return res.sendStatus(401);req.userName=req.get('authorization');next();},verifyToken(req,res,next){if(req.get('authorization')!=='xxz')return res.sendStatus(403);req.adminName='xxz';next();},canSend:async()=>({ok:!options.denied}),banError:()=>options.banned?{status:403,message:'禁言'}:null,publish(){},notifyConsumed:(sender,peer)=>notifications.push({sender,peer}),audit:async()=>{},setPro:async(actor,active)=>{pro.push({actor,active});return{ok:true};}});app.use(feature.router);return{app,feature,tables,files,calls,pro,notifications};
}
async function image(){return sharp({create:{width:3,height:2,channels:3,background:'#18aa88'}}).png().toBuffer();}
function send(f,bytes,client='client0001'){return request(f.app).post('/api/chat/flash/send').set('Authorization','actor').field('target_user','peer').field('client_id',client).attach('image',bytes,{filename:'original.png',contentType:'image/png'});}
function open(f,id,actor='peer'){return request(f.app).post('/api/chat/flash/open').set('Authorization',actor).send({message_id:id});}
test('authenticated encryption preserves original bytes and rejects altered ciphertext',()=>{const original=crypto.randomBytes(1024);const s=seal(original);assert.notDeepEqual(s.bytes,original);assert.deepEqual(unseal(s.bytes,s.key,s.iv,s.tag),original);s.bytes[0]^=1;assert.throws(()=>unseal(s.bytes,s.key,s.iv,s.tag));});
test('flash routes require authentication; admin controls reject ordinary users',async()=>{const f=fixture();await request(f.app).get('/api/chat/flash/quota').expect(401);await request(f.app).post('/api/chat/flash/open').expect(401);await request(f.app).get('/admin/flash-photos').set('Authorization','actor').expect(403);await request(f.app).post('/admin/flash-photos').set('Authorization','actor').send({free_daily:100,pro_daily:100}).expect(403);assert.equal(f.calls.length,0);});
test('send returns no URL/key/thumbnail, stores private ciphertext, and retries charge once',async()=>{const f=fixture(),bytes=await image();const r=await send(f,bytes).expect(200);assert.equal(r.body.ok,true);assert.equal(f.files.size,1);assert.notDeepEqual([...f.files.values()][0],bytes);assert.doesNotMatch(JSON.stringify(r.body),/key_material|storage_path|https:|p_key|base64/);const again=await send(f,bytes).expect(200);assert.equal(again.body.message.id,r.body.message.id);assert.equal(again.body.idempotent,true);assert.equal(f.calls.filter(c=>c[0]==='dm_flash_send').length,1);});
test('first party view consumes globally before download; concurrent second view cannot recover bytes',async()=>{const f=fixture(),bytes=await image(),r=await send(f,bytes);await open(f,r.body.message.id,'outsider').expect(404);assert.ok(f.tables.dm_flash_photos[0].key_material);const results=await Promise.all([open(f,r.body.message.id),open(f,r.body.message.id,'actor')]);assert.deepEqual(results.map(r=>r.status).sort(),[200,410]);const view=results.find(r=>r.status===200);assert.deepEqual(view.body,bytes);assert.match(view.headers['cache-control'],/no-store/);assert.equal(view.headers['x-flash-duration'],'3000');assert.equal(f.tables.dm_flash_photos[0].key_material,null);assert.equal(f.files.size,0);assert.deepEqual(f.notifications,[{sender:'actor',peer:'peer'}]);await open(f,r.body.message.id).expect(410);});
test('failed delivery burns the flash and cannot reopen; failed object removal does not restore key',async()=>{const f=fixture({downloadError:true}),r=await send(f,await image());await open(f,r.body.message.id).expect(410);await open(f,r.body.message.id).expect(410);assert.equal(f.tables.dm_flash_photos[0].key_material,null);const g=fixture({removeError:true}),s=await send(g,await image());await open(g,s.body.message.id).expect(200);assert.equal(g.files.size,1);assert.equal(g.tables.dm_flash_photos[0].key_material,null);await open(g,s.body.message.id).expect(410);});
test('lost commit response preserves private ciphertext and retry returns existing message',async()=>{const f=fixture({commitResponseLost:true}),bytes=await image();await send(f,bytes).expect(503);assert.equal(f.files.size,1);assert.equal(f.tables.dm_flash_photos.length,1);const retry=await send(f,bytes).expect(200);assert.equal(retry.body.idempotent,true);await open(f,retry.body.message.id).expect(200);});
test('daily fourth send is denied without upload; malformed/static-invalid and denied relationships never write',async()=>{const bytes=await image(),f=fixture();for(let i=0;i<3;i++)await send(f,bytes,'client000'+i).expect(200);await send(f,bytes,'client0004').expect(429);assert.equal(f.files.size,3);await request(f.app).post('/api/chat/flash/open').set('Authorization','actor').send({message_id:'../object'}).expect(400);const g=fixture();await send(g,Buffer.from('<svg/>')).expect(415);const denied=fixture({denied:true});await send(denied,bytes).expect(403);const banned=fixture({banned:true});await send(banned,bytes).expect(403);assert.equal(g.files.size+denied.files.size+banned.files.size,0);});
test('admin validates personal/global bounds, preserves inherited null, supports Pro, explicit uniform override',async()=>{const f=fixture();await request(f.app).post('/admin/flash-photos').set('Authorization','xxz').send({user_name:'actor',daily_limit:10001}).expect(400);assert.equal(f.pro.length,0);await request(f.app).post('/admin/flash-photos').set('Authorization','xxz').send({user_name:'actor',daily_limit:null,pro:true}).expect(200);assert.deepEqual(f.pro,[{actor:'actor',active:true}]);assert.equal(f.tables.dm_flash_limits[0].daily_limit,null);await request(f.app).post('/admin/flash-photos').set('Authorization','xxz').send({free_daily:6,pro_daily:12,apply_all:true}).expect(200);assert.deepEqual(f.calls.at(-1),['dm_flash_configure',{p_free:6,p_pro:12,p_override_all:true}]);await request(f.app).post('/admin/flash-photos').set('Authorization','xxz').send({free_daily:-1,pro_daily:12}).expect(400);});
test('cleanup keeps original consumption time and retries other objects after one failure',async()=>{const f=fixture({removeError:true});for(let i=0;i<2;i++){const r=await send(f,await image(),'sweep000'+i);await open(f,r.body.message.id);}await f.feature.sweep();assert.equal(f.calls.filter(c=>c[0]==='remove').length,2);f.tables.dm_flash_photos.forEach(r=>r.consumed_at=new Date(Date.now()-180000).toISOString());const times=f.tables.dm_flash_photos.map(r=>r.consumed_at);await f.feature.sweep();assert.deepEqual(f.tables.dm_flash_photos.map(r=>r.consumed_at),times);assert.equal(f.calls.filter(c=>c[0]==='remove').length,4);});
