const {test,expect}=require('@playwright/test');
test.beforeEach(async({page})=>{await page.setViewportSize({width:390,height:844});await page.route('**/api/**',r=>r.fulfill({json:{ok:true,data:[],token:'test-token'}}));});
async function open(page){await page.goto('/');await page.waitForFunction(()=>typeof requestPostLocation==='function');await page.evaluate(()=>{window.currentUser='location_tester';window.ensureProtectedOperationAuth=async()=>({ok:true,token:'test-token'});window.xtjProtectedFetch=(url,opts)=>fetch(url,opts);});}
test('post location is requested only after a click, can be selected and removed',async({page,context})=>{
 await context.grantPermissions(['geolocation']);await context.setGeolocation({latitude:31.2304,longitude:121.4737,accuracy:18});let calls=0;
 await page.route('**/api/location/reverse',r=>{calls++;const b=r.request().postDataJSON();expect(b.latitude).toBeCloseTo(31.2304,4);expect(b.longitude).toBeCloseTo(121.4737,4);return r.fulfill({json:{ok:true,address:'上海市',display_name:'上海市',province:'上海',city:'上海',options:[{name:'上海市',address:'上海市',latitude:31.2304,longitude:121.4737}]}});});
 await open(page);await page.waitForTimeout(150);expect(calls).toBe(0);await page.locator('#postLocationAddBtn').click();await expect.poll(()=>calls).toBe(1);await expect(page.locator('#postLocationPanel')).toBeVisible();const option=page.locator('#postLocationOptions [role=button]').first();await option.click();await expect(page.locator('#postLocationPreview')).toBeVisible();await page.locator('#postLocationPreview button').click();await expect(page.locator('#postLocationPreview')).toBeHidden();
});
test('denied post location restores the clickable button with readable feedback',async({page})=>{await page.addInitScript(()=>Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition:(_ok,error)=>error({code:1,message:'denied'})}}));await open(page);await page.locator('#postLocationAddBtn').click();await expect(page.locator('#postLocationAddBtn')).toBeEnabled();await expect(page.locator('#postLocationPanel')).toBeHidden();await expect(page.locator('body')).toContainText(/拒绝|允许|定位权限/);});
test('old location sharing preference never triggers passive tracking after a refresh',async({page})=>{await page.addInitScript(()=>{localStorage.setItem('xtj_location_sharing_enabled','1');window.locationReads=0;Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition(){locationReads++},watchPosition(){locationReads++;return 7},clearWatch(){}}});});await open(page);await page.reload();await page.waitForFunction(()=>typeof requestPostLocation==='function');expect(await page.evaluate(()=>locationReads)).toBe(0);await expect(page.locator('#profileLocationToggle')).toHaveCount(0);});
