'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const url='https://xtj.test/api/photo/11111111-1111-4111-8111-111111111111/media';
function runtime(){let calls=0,epoch=1,now=100000;const window={API_BASE:'https://xtj.test',currentUser:'alice',__xtjGetAuthEpoch:()=>epoch,refreshUserToken:async()=>{calls++;return 'access';}};vm.runInNewContext(fs.readFileSync('js/media-session.js','utf8'),{window,location:{href:'https://xtj.test/',origin:'https://xtj.test'},URL,Date:{now:()=>now},Promise});return{window,get calls(){return calls;},advance(){now+=13*60000;},switchUser(owner){window.currentUser=owner;epoch++;}};}
test('media session renewals coalesce, cache per identity, and renew before cookie expiry',async()=>{const r=runtime();assert.deepEqual(await Promise.all(Array.from({length:4},()=>r.window.xtjEnsureMediaSession(url))),[true,true,true,true]);assert.equal(r.calls,1);await r.window.xtjEnsureMediaSession(url);assert.equal(r.calls,1);r.advance();await r.window.xtjEnsureMediaSession(url);assert.equal(r.calls,2);r.switchUser('bob');await r.window.xtjEnsureMediaSession(url);assert.equal(r.calls,3);});
test('guest wall access fails while public post and granted share media need no login refresh',async()=>{const r=runtime();r.switchUser('');assert.equal(await r.window.xtjEnsureMediaSession(url),false);assert.equal(await r.window.xtjEnsureMediaSession(url.replace('/photo/','/post/')+'/0'),true);assert.equal(await r.window.xtjEnsureMediaSession('https://foreign.test'+new URL(url).pathname),true);assert.equal(await r.window.xtjEnsureMediaSession('https://xtj.test/api/photo/shared/grant/photo/media'),true);assert.equal(r.calls,0);});
test('late refresh cannot authenticate an A to B to A identity cycle',async()=>{const r=runtime();let release;r.window.refreshUserToken=()=>new Promise(resolve=>release=resolve);const task=r.window.xtjEnsureMediaSession(url);await Promise.resolve();r.switchUser('bob');r.switchUser('alice');release('access');assert.equal(await task,false);});
test('image recovery is bounded and never puts login credentials in the URL',async()=>{const r=runtime();const img={isConnected:true,src:url,getAttribute(){return this.src;}};assert.equal(r.window.xtjRecoverMediaImage(img,url),true);assert.equal(r.window.xtjRecoverMediaImage(img,url),false);await new Promise(setImmediate);assert.match(img.src,/xtj_retry=/);assert.equal(new URL(img.src).pathname,new URL(url).pathname);assert.doesNotMatch(img.src,/access|token/);assert.equal(r.calls,1);});
test('a later expiry can recover the same image without creating an immediate retry loop',async()=>{const r=runtime();const img={isConnected:true,src:url,getAttribute(){return this.src;}};r.window.xtjRecoverMediaImage(img,url);await new Promise(setImmediate);r.advance();assert.equal(r.window.xtjRecoverMediaImage(img,url),true);assert.equal(r.window.xtjRecoverMediaImage(img,url),false);await new Promise(setImmediate);assert.equal(r.calls,2);});
test('staggered failures reuse a successful repair instead of rotating a session per image',async()=>{const r=runtime();for(let n=0;n<12;n++){const img={isConnected:true,src:url,getAttribute(){return this.src;}};assert.equal(r.window.xtjRecoverMediaImage(img,url),true);await new Promise(setImmediate);assert.match(img.src,/xtj_retry=/);}assert.equal(r.calls,1);});
test('recovery cannot restore an image after its owner, source, or connection changes',async()=>{for(const mutation of ['owner','source','connection']){const r=runtime();let release;r.window.refreshUserToken=()=>new Promise(resolve=>release=resolve);const img={isConnected:true,src:url,getAttribute(){return this.src;}};r.window.xtjRecoverMediaImage(img,url);await Promise.resolve();if(mutation==='owner')r.switchUser('bob');if(mutation==='source')img.src='replacement';if(mutation==='connection')img.isConnected=false;const before=img.src;release('access');await new Promise(setImmediate);assert.equal(img.src,before);}});
test('failed renewal reports failure without publishing an authenticated URL',async()=>{const r=runtime();r.window.refreshUserToken=async()=>{throw Error('offline');};let failed=0;const img={isConnected:true,src:url,getAttribute(){return this.src;}};r.window.xtjRecoverMediaImage(img,url,()=>failed++);await new Promise(setImmediate);assert.equal(failed,1);assert.equal(img.src,url);});
