'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=f=>fs.readFileSync('js/photo-wall/'+f,'utf8');
function inject(s,code){return s.replace(/\}\)\(\);\s*$/,code+'\n})();');}
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};}
async function until(f){for(let i=0;i<40&&!f();i++)await new Promise(r=>setImmediate(r));assert.ok(f(),'expected deferred operation to start');}
function classes(){const values=new Set();return{add(...n){n.forEach(x=>values.add(x));},remove(...n){n.forEach(x=>values.delete(x));},contains:n=>values.has(n),toggle(){}};}
function image(url){const attrs=new Map([['data-src',url]]);return{isConnected:true,complete:false,naturalWidth:0,naturalHeight:0,style:{},classList:classes(),getAttribute:n=>attrs.get(n),removeAttribute:n=>attrs.delete(n),getBoundingClientRect:()=>({top:0,bottom:100}),set src(v){this.value=v;},get src(){return this.value;}};}
function images(){const timers=new Map();let seq=0;const window={pwSortKey:'date_desc'},ctx={window,document:{getElementById:()=>null},console,Set,Map,Date,URL,setTimeout(f,ms){const id=++seq;timers.set(id,{f,ms});return id;},clearTimeout:id=>timers.delete(id)};vm.runInNewContext(inject(source('render.js'),'window.audit={queueImage,pumpImages,get active(){return activeLoads;},get pending(){return pendingImgs.length;},nextGeneration(){_pwRenderGeneration++;activeLoads=0;pendingImgs=[];}};'),ctx);return{api:window.audit,timers};}
test('wall network failure preserves the original URL and provides a working retry',()=>{const{api}=images(),img=image('https://xtj.test/a.jpg');api.queueImage(img);api.pumpImages();img.onerror();assert.equal(img.getAttribute('data-src'),'https://xtj.test/a.jpg');assert.equal(typeof img.onclick,'function');img.onclick({stopPropagation(){}});assert.equal(img.src,'https://xtj.test/a.jpg');assert.equal(api.active,1);});
test('wall timeout starts the next queued photo without another observer callback',()=>{const{api,timers}=images(),a=image('https://xtj.test/a.jpg'),b=image('https://xtj.test/b.jpg');api.queueImage(a);api.pumpImages();api.queueImage(b);const timer=[...timers.values()].find(t=>t.ms===10000);timer.f();assert.equal(b.src,'https://xtj.test/b.jpg');assert.equal(api.pending,0);assert.equal(typeof a.onclick,'function');});
function uploadRuntime(fetchImpl){const storage=new Map(),listeners={},timers=new Map();let timerSeq=0,epoch=1;const window={currentUser:'A',__xtjGetAuthEpoch:()=>epoch,addEventListener(n,f){listeners[n]=f;},getUserAuthHeaders:async()=>({Authorization:'Bearer A'}),safeStorage:{get:k=>storage.get(k)||null,set:(k,v)=>storage.set(k,v)},showToast(){}};const context={window,document:{readyState:'loading',addEventListener(){},getElementById:()=>null},localStorage:{getItem:()=>null},console,URL,crypto:{randomUUID:()=> 'audit-upload'},AbortController,setTimeout(f,ms){if(ms<1000)return setTimeout(f,ms);const id=++timerSeq;timers.set(id,{f,ms});return id;},clearTimeout(id){timers.delete(id);},setInterval:()=>0,clearInterval(){},fetch:fetchImpl};vm.runInNewContext(inject(source('upload-ui.js'),'window.audit={state,uploadOnePhotoWallFile,savePendingPhotoUpload,photoFetch};'),context);return{window,storage,timers,change(owner){window.currentUser=owner;epoch++;},api:window.audit};}
function job(){return{file:{name:'a.jpg',type:'image/jpeg',size:5},uploadId:'audit-upload',identity:{owner:'A',epoch:1}};}
test('photo upload never sends A original under B after delayed authentication',async()=>{const auth=deferred();let started=false;const calls=[];const r=uploadRuntime(async(url,options)=>{calls.push({url,options});return{ok:true,json:async()=>({ok:true,public_url:'https://xtj.test/a.jpg',data:{id:'photo'}})};});r.window.getUserAuthHeaders=()=>{started=true;return auth.promise;};const task=r.api.uploadOnePhotoWallFile(job(),new AbortController().signal);await until(()=>started);r.change('B');auth.resolve({Authorization:'Bearer B'});await assert.rejects(task,/identity_changed/);assert.equal(calls.length,0);});
test('photo upload fences an A to B to A cycle even if the username matches again',async()=>{const auth=deferred();let started=false,calls=0;const r=uploadRuntime(async()=>{calls++;return{ok:true,json:async()=>({ok:true,public_url:'https://xtj.test/a.jpg',data:{id:'photo'}})};});r.window.getUserAuthHeaders=()=>{started=true;return auth.promise;};const task=r.api.uploadOnePhotoWallFile(job(),new AbortController().signal);await until(()=>started);r.change('B');r.change('A');auth.resolve({Authorization:'Bearer A-new'});await assert.rejects(task,/identity_changed/);assert.equal(calls,0);});
test('pending reconciliation retains uploads added while status is in flight',async()=>{const status=deferred();let started=false;const r=uploadRuntime(async()=>{started=true;return status.promise;});r.api.savePendingPhotoUpload({uploadId:'old',path:'photos/old.jpg',owner:'A'});const work=r.window.reconcilePendingPhotoUploads();await until(()=>started);r.api.savePendingPhotoUpload({uploadId:'new',path:'photos/new.jpg',owner:'A'});status.resolve({ok:true,json:async()=>({status:'processing'})});await work;assert.deepEqual(JSON.parse(r.storage.get('xtj_photo_upload_pending')).map(x=>x.uploadId).sort(),['new','old']);});
function sizeRuntime(fetchImpl){const code=source('preview-hotfix.js');const start=code.search(/  (?:async )?function fetchPhotoFileSize\(photo\)/);const end=code.indexOf('  function bindInfoModal()',start);const ctx={fetch:fetchImpl,AbortController,setTimeout:()=>1,clearTimeout(){}};vm.runInNewContext(code.slice(start,end)+'\nthis.getSize=fetchPhotoFileSize;',ctx);return ctx.getSize;}
test('photo info persists the fetched original byte size for rendering and reuse',async()=>{let calls=0;const getSize=sizeRuntime(async()=>{calls++;return{ok:true,headers:{get:n=>n==='content-length'?'512':null}};});const photo={imageUrl:'https://xtj.test/a.jpg'};assert.equal(await getSize(photo),512);assert.equal(photo.fileSize,512);assert.equal(await getSize(photo),512);assert.equal(calls,1);});
test('photo info range fallback uses total original size and cancels the response body',async()=>{let cancelled=false;const calls=[];const getSize=sizeRuntime(async(url,options)=>{calls.push(options);return options.method==='HEAD'?{ok:true,headers:{get:()=>null}}:{ok:true,status:206,headers:{get:n=>n==='content-range'?'bytes 0-0/2048':n==='content-length'?'1':null},body:{cancel:async()=>{cancelled=true;}}};});assert.equal(await getSize({imageUrl:'https://xtj.test/a.jpg'}),2048);assert.equal(calls[1].headers.Range,'bytes=0-0');assert.equal(cancelled,true);});
test('photo delete body stalls remain bounded and reconcile authoritative deleted status',async()=>{const timers=new Map();let seq=0,bodyStarted=false;const code=source('data.js'),start=code.indexOf('  async function deleteCloudPhoto(item)'),end=code.indexOf('  function canDeletePhotoWallPhoto',start);const ctx={window:{currentUser:'A',__xtjGetAuthEpoch:()=>1,getUserAuthHeaders:async()=>({})},console,AbortController,apiUrl:p=>p,setTimeout(f,ms){const id=++seq;timers.set(id,{f,ms});return id;},clearTimeout:id=>timers.delete(id),fetch:async(url,options)=>url.includes('delete-status')?{ok:true,json:async()=>({status:'deleted'})}:{ok:true,json:()=>{bodyStarted=true;return new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'})),{once:true}));}}};vm.runInNewContext(code.slice(start,end)+'\nthis.remove=deleteCloudPhoto;',ctx);const task=ctx.remove({id:'photo'});await until(()=>bodyStarted);const timeout=[...timers.values()].find(t=>t.ms===20000);assert.ok(timeout,'delete timeout must cover the body');timeout.f();assert.equal((await task).ok,true);assert.equal(timers.size,0);});

test('photo status requests bound stalled bodies and remove their abort listeners',async()=>{let started=false;const r=uploadRuntime(async(url,options)=>({ok:true,json:()=>{started=true;return new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'})),{once:true}));}}));const response=await r.api.photoFetch('/api/photo/status',{});const body=response.json();await until(()=>started);const timer=[...r.timers.values()].find(t=>t.ms===25000);assert.ok(timer,'the timeout must remain active through body consumption');timer.f();await assert.rejects(body,{name:'AbortError'});assert.equal(r.timers.size,0);});

test('an old grid timeout cannot replace a reused image or release its new loading slot',()=>{const{api,timers}=images(),img=image('https://xtj.test/a.jpg');api.queueImage(img);api.pumpImages();const oldTimer=[...timers.values()].find(t=>t.ms===10000);api.nextGeneration();img._pwQueued=false;api.queueImage(img);api.pumpImages();const onload=img.onload;oldTimer.f();assert.equal(img.src,'https://xtj.test/a.jpg');assert.equal(img.onload,onload);assert.equal(api.active,1);});
test('grid warming fills four available slots but never exceeds the loading limit',()=>{const{api}=images();for(let i=0;i<5;i++)api.queueImage(image('https://xtj.test/'+i+'.jpg'));api.pumpImages();assert.equal(api.active,4);assert.equal(api.pending,1);});
