'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const {claimPhotoUpload,ownsPhotoUpload,ownedPhotoUploadPaths}=require('../render-api/photo-ownership');const {validatePhotoCreatePayload}=require('../render-api/photo-create');
function database(){const rows=[],files=new Set();let unavailable=false;return {rows,files,storage:{from(){return {async exists(path){if(unavailable)throw Error("storage unavailable");return {data:files.has(path),error:null};}};}},setUnavailable(){unavailable=true;},from(table){assert.equal(table,'photo_upload_registry');const filters=[];const q={select(){return this;},eq(k,v){filters.push(r=>r[k]===v);return this;},in(k,v){filters.push(r=>v.includes(r[k]));return this;},async insert(row){if(unavailable)return {error:{code:'timeout'}};if(rows.some(r=>r.storage_path===row.storage_path))return {error:{code:'23505'}};rows.push(row);return {error:null};},async maybeSingle(){return unavailable?{error:{code:'timeout'}}:{data:rows.find(r=>filters.every(f=>f(r))) || null,error:null};},then(resolve,reject){return Promise.resolve(unavailable?{error:{code:'timeout'}}:{data:rows.filter(r=>filters.every(f=>f(r))),error:null}).then(resolve,reject);}};return q;}};}
test('exact path ownership precedes upload and cannot be reassigned using a known upload ID',async()=>{
 const d=database(),path='photos/shared-id_1700000000000_rand_a.jpg';assert.equal(await claimPhotoUpload(d,path,'A','shared-id'),true);assert.equal(await claimPhotoUpload(d,path,'B','shared-id'),false);assert.equal(await ownsPhotoUpload(d,path,'B','shared-id'),false);assert.equal(await ownsPhotoUpload(d,path,'A','other-id'),false);assert.equal(await ownsPhotoUpload(d,path,'A','shared-id'),true);
 d.files.add('photos/legacy-a.jpg');assert.equal(await claimPhotoUpload(d,'photos/legacy-a.jpg','B','known-id'),false);assert.equal(await ownsPhotoUpload(d,'photos/legacy-a.jpg','B','known-id'),false);
 await claimPhotoUpload(d,'photos/b.jpg','B','shared-id');assert.deepEqual(await ownedPhotoUploadPaths(d,[path,'photos/b.jpg','photos/unregistered.jpg'],'B','shared-id'),['photos/b.jpg']);
 d.setUnavailable();await assert.rejects(ownsPhotoUpload(d,path,'B','shared-id'));await assert.rejects(claimPhotoUpload(d,path,'B','shared-id'));await assert.rejects(ownedPhotoUploadPaths(d,[path],'B','shared-id'));
});
test('deleting a chosen filename cannot guess another user’s original ending in _thumb',()=>{
 const source=fs.readFileSync(require.resolve('../render-api/server'),'utf8'),start=source.indexOf('function collectPhotoStoragePaths('),end=source.indexOf('\nasync function hardDeleteContent',start);const context={URL};vm.createContext(context);vm.runInContext(source.slice(start,end),context);
 const origin='https://example.supabase.co',base='photos/upload-id_1700000000000_rand_photo.jpg',victim=base.replace('.jpg','_thumb.jpg');const body={upload_id:'upload-id',media_url:origin+'/storage/v1/object/public/uploads/'+base,mime_type:'image/jpeg',file_size:100,original_size:100};const input=validatePhotoCreatePayload(body,origin);assert.equal(input.ok,true);
 const paths=Array.from(context.collectPhotoStoragePaths({content:input.content,media_url:body.media_url}));assert.deepEqual(paths,[base]);assert.ok(!paths.includes(victim));
 const legacy=Array.from(context.collectPhotoStoragePaths({content:JSON.stringify({storagePath:base,thumb:'photos/thumbs/known.webp'}),media_url:body.media_url}));assert.deepEqual(legacy,[base,'photos/thumbs/known.webp']);
});
