'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),express=require('express'),crypto=require('node:crypto');
const {installPhotoSocial,isPublicPhoto}=require('../render-api/photo-social');
const {validatePhotoCreatePayload}=require('../render-api/photo-create');
const photoId='123e4567-e89b-42d3-a456-000000000081';
function db(){
 const rows={posts:[{id:photoId,media_type:'__photo_wall__',media_url:'https://example/photo.jpg',content:'{}',visibility:'public'}],likes:[],comments:[],photo_viewers:[]};let fail=false;
 return {rows,setFail(){fail=true;},from(table){let filters=[],head=false,limit=100,operation=null;const q={
  select(fields,opts){head=!!(opts&&opts.head);return q;},eq(k,v){filters.push(r=>r[k]===v);return q;},order(){return q;},limit(n){limit=n;return q;},or(){return q;},
  upsert(row){operation=()=>{if(!rows[table].some(r=>r.post_id===row.post_id&&r.user_name===row.user_name))rows[table].push({...row,id:crypto.randomUUID()});};return q;},
  insert(row){operation=()=>{rows[table].push({...row,id:crypto.randomUUID(),created_at:new Date().toISOString()});};return q;},
  delete(){operation=()=>{rows[table]=rows[table].filter(r=>!filters.every(f=>f(r)));};return q;},
  result(){if(fail)return {error:{code:'DB_OFFLINE'}};if(operation){operation();operation=null;}const data=rows[table].filter(r=>filters.every(f=>f(r)));return {data:head?null:data.slice(0,limit),count:data.length,error:null};},
  async maybeSingle(){const r=q.result();return {...r,data:r.data&&r.data[0]||null};},async single(){return q.maybeSingle();},then(resolve,reject){return Promise.resolve(q.result()).then(resolve,reject);}};return q;}};
}
async function fixture(t){const data=db(),app=express();app.use(express.json());function auth(req,res,next){if(!req.headers['x-user'])return res.sendStatus(401);req.userName=req.headers['x-user'];next();}installPhotoSocial(app,{supabase:data,authenticateUser:auth,optionalAuth(req,res,next){req.userName=req.headers['x-user']||'';next();},rateLimit(){return(req,res,next)=>next();},userBanError(req){return req.userName==='banned'?{status:403,message:'禁止互动'}:null;}});const server=app.listen(0);await new Promise(resolve=>server.once('listening',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));const base='http://127.0.0.1:'+server.address().port;return {data,request(path,user,body){return fetch(base+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(user?{'x-user':user}:{})},body:body?JSON.stringify(body):undefined});}};}
test('photo caption round-trips safe text and rejects unsupported types, excessive text and controls',()=>{const body={media_url:'https://example.supabase.co/storage/v1/object/public/uploads/photos/my.jpg',file_size:120,original_size:120,mime_type:'image/jpeg',upload_id:'upload-abc',caption:'雪山\n<script>只是文字</script>'};const result=validatePhotoCreatePayload(body,'https://example.supabase.co');assert.equal(result.ok,true);assert.equal(JSON.parse(result.content).caption,body.caption);for(const caption of [{text:'hi'},'a'.repeat(1001),'x\0y'])assert.equal(validatePhotoCreatePayload({...body,caption},'https://example.supabase.co').ok,false);});
test('photo social operations persist authenticated identity, idempotent likes, comments and exact counts',async t=>{const f=await fixture(t),path='/api/photo/'+photoId;let response=await f.request(path+'/like','B',{liked:true,user_name:'A'});assert.equal(response.status,200);assert.equal(f.data.rows.likes[0].user_name,'B');await f.request(path+'/like','B',{liked:true});assert.equal(f.data.rows.likes.length,1);response=await f.request(path+'/comments','B',{content:'<img onerror=bad>\n很漂亮',user_name:'A'});assert.equal(response.status,201);assert.equal(f.data.rows.comments[0].user_name,'B');f.data.rows.photo_viewers.push({photo_id:photoId,viewer_name:'B'});let payload=await(await f.request(path+'/social','B')).json();assert.equal(payload.liked,true);assert.equal(payload.like_count,1);assert.equal(payload.comment_count,1);assert.equal(payload.views,1);assert.equal(payload.comments[0].content,'<img onerror=bad>\n很漂亮');assert.equal((await f.request(path+'/social')).status,401);payload=await(await f.request(path+'/social','A')).json();assert.equal(payload.liked,false);await f.request(path+'/like','A',{liked:false});assert.equal(f.data.rows.likes.length,1);await f.request(path+'/like','B',{liked:false});assert.equal(f.data.rows.likes.length,0);});
test('private, deleted and internal rows cannot be probed or interacted with, and unavailable DB fails closed',async t=>{const f=await fixture(t),path='/api/photo/'+photoId;assert.equal((await f.request(path+'/like','',{liked:true})).status,401);assert.equal((await f.request(path+'/like','banned',{liked:true})).status,403);for(const patch of [{visibility:'private'},{is_deleted:true},{media_type:'__dm__'},{content:'{"__pw_del__":true}'},{media_url:'__deleted__'}]){Object.assign(f.data.rows.posts[0],{visibility:'public',is_deleted:false,media_type:'__photo_wall__',content:'{}',media_url:'https://example/photo.jpg'},patch);assert.equal((await f.request(path+'/social','B')).status,404);assert.equal((await f.request(path+'/like','B',{liked:true})).status,404);assert.equal((await f.request(path+'/comments','B',{content:'hi'})).status,404);}f.data.setFail();assert.equal((await f.request(path+'/social','B')).status,503);assert.equal(f.data.rows.likes.length,0);assert.equal(f.data.rows.comments.length,0);assert.equal(isPublicPhoto({media_type:'__photo_wall__',content:'invalid'}),false);});
test('photo viewer identity is taken from authentication, never the body or a device identifier',async()=>{
 const fs=require('node:fs'),vm=require('node:vm'),source=fs.readFileSync(require.resolve('../render-api/server'),'utf8');const start=source.indexOf("app.post('/api/photo/view',"),end=source.indexOf('\n});',start)+4;let handler,calls=[];
 const context={console,Number,normalizePostId:id=>id===photoId?id:null,sanitizeError:()=> 'database error',authenticateUser(){},rateLimit(){return()=>{};},supabase:{from(){return {select(){return this;},eq(){return this;},async maybeSingle(){return {data:{id:photoId,media_type:'__photo_wall__',visibility:'public',is_deleted:false},error:null};}};},async rpc(name,args){calls.push({name,args});return {data:1,error:null};}},app:{post(path,...middleware){handler=middleware.at(-1);}}};vm.createContext(context);vm.runInContext(source.slice(start,end),context);
 const res={status(code){this.code=code;return this;},json(body){this.body=body;return this;}};await handler({userName:'B',body:{photo_id:photoId,user_name:'A',viewer_name:'A',device_id:'A-device'}},res);assert.equal(res.body.views,1);assert.equal(calls[0].name,'record_photo_view');assert.equal(calls[0].args.p_viewer_name,'B');assert.match(source.slice(start,end),/authenticateUser/);
});
