const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path'),sharp=require('sharp');
const source=file=>fs.readFileSync(path.join(__dirname,'..',file),'utf8');
const ids=['123e4567-e89b-42d3-a456-000000000091','123e4567-e89b-42d3-a456-000000000092'];
async function storyFixture(page){
 await page.route('**/story-fixture',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><div id="photoGrid"></div>'}));await page.goto('/story-fixture');
 await page.addStyleTag({content:source('css/style.css')+source('css/ui-shell.css')+source('css/photo-preview.css')});
 const image=await sharp({create:{width:1600,height:900,channels:3,background:'#608b80'}}).jpeg().toBuffer();await page.route('**/story-*.jpg',r=>r.fulfill({contentType:'image/jpeg',body:image}));await page.route('**/api/avatar/public/*',r=>r.fulfill({json:{avatar_url:'http://127.0.0.1:4176/story-0.jpg'}}));
 await page.addScriptTag({content:'window.currentUser="B";window.showToast=function(){};window.updateAmbientBackground=function(){};window.__socialCalls=[];window.__views={};window.__liked={};window.__comments={};window.xtjProtectedFetch=async function(url,options={}){window.__socialCalls.push({url,body:options.body});let body={ok:true};let id=url.match(/photo\\/([^/]+)\\//)?.[1]||"";if(url.endsWith("/social"))body={ok:true,like_count:window.__liked[id]?1:0,liked:!!window.__liked[id],comment_count:(window.__comments[id]||[]).length,views:window.__views[id]?1:0,comments:window.__comments[id]||[],has_more:false};else if(url.endsWith("/like")){window.__liked[id]=JSON.parse(options.body).liked;body={ok:true,like_count:window.__liked[id]?1:0,liked:window.__liked[id]};}else if(url.endsWith("/comments")){const text=JSON.parse(options.body).content;body={ok:true,comment:{id:"123e4567-e89b-42d3-a456-000000000099",user_name:"B",content:text,created_at:new Date().toISOString()}};(window.__comments[id]||(window.__comments[id]=[])).unshift(body.comment);}else if(url==="/api/photo/view"){id=JSON.parse(options.body).photo_id;window.__views[id]=1;body={ok:true,views:1,recorded:true};}return new Response(JSON.stringify(body),{status:200});};'+source('js/photo-wall/data.js')+source('js/photo-wall/story.js')+source('js/photo-wall/preview.js')+source('js/photo-wall/preview-hotfix.js')});
 await page.evaluate(ids=>{window.__photos=ids.map((id,i)=>({id,cloudId:id,username:'A',imageUrl:location.origin+'/story-'+i+'.jpg',timestamp:Date.now(),views:0,caption:i?'第二张照片':'雪山下的一天\n<img src=x onerror=alert(1)>只是文字'}));window.openPhotoPreview(0,window.__photos);},ids);
 await expect(page.locator('#photoPreviewImage')).toHaveCSS('opacity','1');await expect(page.locator('#ppLikeBtn')).toBeEnabled();
}
test('photo story uses bare arrows, transparent close, lower-corner icons and safe caption text',async({page})=>{
 await page.setViewportSize({width:390,height:844});await storyFixture(page);await expect(page.locator('#ppStoryCaption')).toContainText('<img src=x');expect(await page.locator('#ppStoryCaption img').count()).toBe(0);
 for(const selector of ['#ppPrevBtn','#ppNextBtn','#ppInfoBtn','#ppShareBtn','#ppRotateBtn']){const style=await page.locator(selector).evaluate(el=>{let s=getComputedStyle(el),r=el.getBoundingClientRect();return {bg:s.backgroundColor,shadow:s.boxShadow,width:r.width,height:r.height};});expect(style.bg,selector).toBe('rgba(0, 0, 0, 0)');expect(style.shadow).toBe('none');expect(style.width).toBeGreaterThanOrEqual(44);expect(style.height).toBeGreaterThanOrEqual(44);}
 const close=await page.locator('.photo-preview-close').evaluate(el=>({width:el.getBoundingClientRect().width,blur:getComputedStyle(el).backdropFilter||getComputedStyle(el).webkitBackdropFilter}));expect(close.width).toBe(44);expect(close.blur).toContain('3px');
 const toolbar=await page.locator('.pp-preview-toolbar').boundingBox();expect(toolbar.x+toolbar.width).toBeGreaterThan(350);expect(toolbar.y).toBeGreaterThan(740);await expect(page.locator('#ppDeleteBtn')).toBeHidden();await expect(page.locator('#ppStoryAvatar img')).toBeVisible();await page.evaluate(()=>window.renderPhotoStory(window.__photos[0]));await expect(page.locator('#ppStoryAvatar img')).toBeVisible();await page.screenshot({path:'/workspace/scratch/photo-story-'+test.info().project.name+'.png'});
});
test('photo likes and comments persist across switching, failures preserve input and caption stays per-photo',async({page})=>{
 await storyFixture(page);await page.locator('#ppLikeBtn').click();await expect(page.locator('#ppLikeBtn')).toHaveAttribute('aria-pressed','true');await page.locator('#ppCommentBtn').click();await page.locator('#ppCommentInput').fill('<script>只是评论</script>');await page.locator('#ppCommentSend').click();await expect(page.locator('.pp-comment-row')).toContainText('<script>只是评论</script>');expect(await page.locator('.pp-comment-row script').count()).toBe(0);await expect(page.locator('#ppCommentCount')).toHaveText('1');
 await page.locator('#ppCommentsClose').click();await page.locator('#ppNextBtn').click();await expect(page.locator('#ppStoryCaption')).toHaveText('第二张照片');await expect(page.locator('#ppLikeCount')).toHaveText('0');await page.locator('#ppPrevBtn').click();await expect(page.locator('#ppLikeCount')).toHaveText('1');await page.locator('#ppCommentBtn').click();await expect(page.locator('.pp-comment-row')).toHaveCount(1);
 await page.evaluate(()=>{const original=window.xtjProtectedFetch;window.xtjProtectedFetch=(url,options)=>url.endsWith('/comments')?Promise.resolve(new Response(JSON.stringify({ok:false,error:'暂时无法发送'}),{status:503})):original(url,options);});await page.locator('#ppCommentInput').fill('保留这条评论');await page.locator('#ppCommentSend').click();await expect(page.locator('#ppCommentError')).toHaveText('暂时无法发送');await expect(page.locator('#ppCommentInput')).toHaveValue('保留这条评论');await expect(page.locator('#ppCommentSend')).toBeEnabled();
});
test('repeat views of one account count once and preloading never records a neighbouring photo',async({page})=>{
 await storyFixture(page);await expect(page.locator('#photoPreviewViewsCount')).toHaveText('1');let calls=await page.evaluate(()=>window.__socialCalls.filter(c=>c.url==='/api/photo/view'));expect(calls).toHaveLength(1);expect(JSON.parse(calls[0].body).photo_id).toBe(ids[0]);
 await page.locator('#ppNextBtn').click();await expect(page.locator('#ppStoryCaption')).toHaveText('第二张照片');await expect(page.locator('#photoPreviewViewsCount')).toHaveText('1');await page.locator('#ppPrevBtn').click();await expect(page.locator('#ppStoryCaption')).toContainText('雪山');calls=await page.evaluate(()=>window.__socialCalls.filter(c=>c.url==='/api/photo/view'));expect(calls).toHaveLength(2);
 await page.evaluate(()=>{window.forceClosePhotoPreview();window.openPhotoPreview(0,window.__photos);});await expect(page.locator('#photoPreviewViewsCount')).toHaveText('1');calls=await page.evaluate(()=>window.__socialCalls.filter(c=>c.url==='/api/photo/view'));expect(calls).toHaveLength(2);
});
test('slide frames never shrink and then enlarge the incoming image',async({page})=>{
 await storyFixture(page);await expect(page.locator('#ppNextImg')).toHaveJSProperty('naturalWidth',1600);
 const widths=await page.evaluate(async()=>{let values=[document.getElementById('ppNextImg').getBoundingClientRect().width];window.ppNextPhoto();let begin=performance.now();while(performance.now()-begin<550){await new Promise(requestAnimationFrame);for(const img of document.querySelectorAll('.pp-slide-img')){if(img.src.endsWith('story-1.jpg')&&getComputedStyle(img).opacity==='1')values.push(img.getBoundingClientRect().width);}}values.push(document.getElementById('photoPreviewImage').getBoundingClientRect().width);return values;});expect(widths.length).toBeGreaterThan(2);expect(Math.max(...widths)-Math.min(...widths)).toBeLessThan(1);
});
async function fullPage(page){await page.addInitScript(()=>localStorage.setItem('xtj_user','A'));await page.route('**/*.supabase.co/**',r=>r.fulfill({json:[]}));await page.route('**/api/**',r=>r.fulfill({json:{ok:true,user_name:'A',token:'signed-A',is_admin:false,restrictions:{},data:[],items:[],conversations:[],friends:[],users:[]}}));await page.goto('/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window._xtjAuthState==='authenticated');}
test('iPad visual viewport, restored outer scroll and orientation keep top controls reachable',async({page})=>{
 await page.setViewportSize({width:1180,height:820});await page.addInitScript(()=>{Object.defineProperty(navigator,'platform',{get:()=> 'MacIntel'});Object.defineProperty(navigator,'maxTouchPoints',{get:()=>5});const vv=new EventTarget();Object.assign(vv,{width:1180,height:680,offsetTop:40,offsetLeft:0,scale:1});Object.defineProperty(window,'visualViewport',{value:vv});window.__vv=vv;});await fullPage(page);await expect(page.locator('html')).toHaveClass(/xtj-ios-viewport/);
 for(const [height,top,width]of [[680,40,1180],[700,0,1180],[960,0,820]]){await page.setViewportSize({width,height:height+80});await page.evaluate(({height,top,width})=>{Object.assign(window.__vv,{height,offsetTop:top,width});window.__vv.dispatchEvent(new Event('resize'));}, {height,top,width});await page.waitForTimeout(100);const rect=await page.locator('.app-container').boundingBox();expect(Math.abs(rect.y-top)).toBeLessThan(1);expect(Math.abs(rect.height-height)).toBeLessThan(1);const button=page.locator('.desktop-nav-item[data-desktop-tab="chat"]');await expect(button).toBeVisible();expect(await button.evaluate(el=>{let r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})).toBe(true);}
 await page.evaluate(()=>window.scrollTo(0,100));expect(await page.evaluate(()=>window.scrollY)).toBe(0);
});
test('chat list retries transient errors without repeated global refresh toasts and keeps cached contacts',async({page})=>{
 await fullPage(page);await page.evaluate(()=>window.switchDockTab('chat'));await expect.poll(()=>page.evaluate(()=>window.dockChatListCacheTime||0)).toBeGreaterThan(0);let attempts=0;await page.evaluate(()=>{window.__chatAttempts=0;window.dockChatListCacheTime=0;const list=document.getElementById('dockChatList');list.setAttribute('data-list-owner','A');list.innerHTML='<div class="chat-list-item" data-chat-user="B">保留的会话</div>';window.__xtjInvalidateDmListShared();const old=window.xtjProtectedFetch;window.xtjProtectedFetch=async(url,options)=>url.startsWith('/api/dm/list')?(window.__chatAttempts++,new Response(JSON.stringify({ok:false,error:'temporary'}),{status:503})):old(url,options);});
 await page.evaluate(()=>window.switchDockTab('chat'));await expect.poll(()=>page.evaluate(()=>window.__chatAttempts)).toBe(2);await expect(page.locator('#dockChatList')).toContainText('保留的会话');await page.waitForTimeout(100);await expect(page.locator('#toastContainer')).not.toContainText('消息列表刷新失败');await page.evaluate(()=>window.fetchDmListShared(180));expect(await page.evaluate(()=>window.__chatAttempts)).toBe(2);
});
