'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),express=require('express'),request=require('supertest');
const {createSecurityActivity,classify}=require('../render-api/security-activity');
function fixture(fail=false){const writes=[];const app=express();app.use(express.json());app.use(createSecurityActivity({supabase:{from(n){assert.equal(n,'posts');return{async insert(row){writes.push(row);return fail?{error:Error('failure')}:{data:row};}};}},getClientIp(){return'203.0.113.10';}}));app.use((req,res,next)=>{if(req.get('Authorization')==='actor'){req.userName='actor';req._clientIpSource='trusted_proxy';}next();});app.use((req,res)=>res.status(Number(req.get('X-Status'))||200).json({ok:true}));return{app,writes};}
test('server action attribution ignores forged identities, payload, credentials and query strings',async()=>{const f=fixture();await request(f.app).post('/api/dm/send?password=secret').set('Authorization','actor').send({user_name:'victim',text:'private message',password:'secret',target:'untrusted'}).expect(200);assert.equal(f.writes.length,1);const row=f.writes[0],event=JSON.parse(row.content).events[0];assert.equal(row.user_name,'actor');assert.equal(event.type,'message_send');assert.equal(event.authority,'server_action');assert.equal(event.ip,'203.0.113.10');assert.equal(event.ip_source,'trusted_proxy');assert.doesNotMatch(JSON.stringify(row),/secret|private message|victim|untrusted/);});
test('authenticated denials are distinct; anonymous and unrelated routes do not become user behavior',async()=>{const f=fixture();await request(f.app).post('/api/photo/delete').set('Authorization','actor').set('X-Status','403');await request(f.app).post('/api/photo/delete').send({user_name:'actor'});await request(f.app).get('/api/dm/messages').set('Authorization','actor');assert.equal(f.writes.length,1);const e=JSON.parse(f.writes[0].content).events[0];assert.equal(e.type,'action_denied');assert.equal(e.target,'photo_delete');assert.equal(e.status,403);});
test('coalesces rapid read events while preserving writes and consented location actions',async()=>{const f=fixture();for(let i=0;i<2;i++)await request(f.app).post('/api/photo/view').set('Authorization','actor');for(let i=0;i<2;i++)await request(f.app).post('/api/chat/flash/send').set('Authorization','actor');await request(f.app).post('/api/user/location').set('Authorization','actor').send({latitude:26,longitude:119});assert.equal(f.writes.length,4);assert.equal(JSON.parse(f.writes.at(-1).content).events[0].type,'location_authorized');assert.doesNotMatch(f.writes.at(-1).content,/latitude|longitude/);});
test('logging failure does not change successful response; semantic delete paths classify correctly',async()=>{const f=fixture(true);await request(f.app).post('/api/dm/send').set('Authorization','actor').expect(200);assert.equal(f.writes.length,1);assert.equal(classify({method:'DELETE',path:'/api/photo/comments/123e4567-e89b-42d3-a456-000000000004'}),'comment_delete');assert.equal(classify({method:'POST',path:'/api/avatar/batch'}),undefined);});
test('admin profile keeps true first/last IP and device times for descending retained login records',async()=>{
 const fs=require('node:fs'),vm=require('node:vm');const source=fs.readFileSync(require.resolve('../render-api/server'),'utf8');const begin=source.indexOf("app.get('/admin/user-profile'");const end=source.indexOf('// ===================== 实时在线用户 API',begin);assert.ok(begin>0&&end>begin);
 const events=['2026-10-01T10:00:00Z','2026-09-30T08:00:00Z'].map(created_at=>({created_at,content:JSON.stringify({ip:'203.0.113.10',device_id:'device_one'})}));let handler;
 const db={from(){let marker;const q={select(){return q;},eq(k,v){if(k==='media_type')marker=v;return q;},order(){return q;},limit(){return q;},async maybeSingle(){return{data:null};},then(resolve){return Promise.resolve({data:marker==='__login_event__'?events:[]}).then(resolve);}};return q;},async rpc(){return{data:{login_count:2}};}};
 vm.runInNewContext(source.slice(begin,end),{app:{get(path,...handlers){handler=handlers.at(-1);}},verifyToken(){},rateLimit(){return()=>{};},supabase:db,USER_INFO_MARKER:'__user_info__',LOGIN_EVENT_MARKER:'__login_event__',USER_BEHAVIOR_MARKER:'__user_behavior__',USER_VISIT_MARKER:'__user_visit__',normalizeDeviceSnapshot:()=>({type:'phone',os:'test',browser:'test'}),logAdminAudit:async()=>{},console,sanitizeError:()=>''});
 let body;await handler({query:{user_name:'actor'},adminName:'xxz'},{json(v){body=v;return this;},status(){return this;}});assert.equal(body.unique_ips[0].first_seen,events[1].created_at);assert.equal(body.unique_ips[0].last_seen,events[0].created_at);assert.equal(body.unique_devices[0].last_seen,events[0].created_at);assert.equal(body.unique_devices[0].first_seen,events[1].created_at);
});
