-- 创建 brain_nodes 表（AI 个人知识库）
CREATE TABLE IF NOT EXISTS brain_nodes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT NOT NULL DEFAULT '',
  raw_content TEXT NOT NULL,
  ai_summary TEXT DEFAULT '',
  tags TEXT[] DEFAULT '{}',
  people TEXT[] DEFAULT '{}',
  node_type TEXT DEFAULT 'note',
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','processing','completed','failed')),
  is_public BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_brain_nodes_user ON brain_nodes(user_name);
CREATE INDEX IF NOT EXISTS idx_brain_nodes_status ON brain_nodes(status);
CREATE INDEX IF NOT EXISTS idx_brain_nodes_tags ON brain_nodes USING GIN(tags);
CREATE INDEX IF NOT EXISTS idx_brain_nodes_people ON brain_nodes USING GIN(people);
CREATE INDEX IF NOT EXISTS idx_brain_nodes_created ON brain_nodes(created_at DESC);

-- RLS（行级安全）
ALTER TABLE brain_nodes ENABLE ROW LEVEL SECURITY;

-- 每个人只能看自己的数据
CREATE POLICY "users_read_own" ON brain_nodes
  FOR SELECT USING (user_name = current_setting('app.user_name', true) OR user_name = '');

-- 每个人只能插入自己的数据
CREATE POLICY "users_insert_own" ON brain_nodes
  FOR INSERT WITH CHECK (user_name = current_setting('app.user_name', true));

-- 每个人只能更新自己的数据
CREATE POLICY "users_update_own" ON brain_nodes
  FOR UPDATE USING (user_name = current_setting('app.user_name', true));

-- 公开数据所有人可读
CREATE POLICY "public_read" ON brain_nodes
  FOR SELECT USING (is_public = true);
