-- ============================================================================
-- 001 基础 schema 快照（仅供全新环境初始化）
-- ----------------------------------------------------------------------------
-- ⚠️ 重要：本文件仅用于「全新环境 / 灾难恢复」从零回放时的基础建表快照。
--    生产库与已应用历史迁移的库【请勿执行】——它们的历史迁移链已隐式存在
--    这些表（posts/likes/comments/bans/blacklist/mutes），重复执行本快照
--    因使用 CREATE TABLE IF NOT EXISTS 不会报错，但无需也不应再执行。
--
-- 背景（审计 07c-infra-build.md 🔴）：历史迁移以 002 开头，缺失 001 基础表
--    定义，核心表 posts/likes/comments/bans/blacklist/mutes 均无 CREATE TABLE
--    迁移；其中 blacklist/mutes 被 032 get_user_restrictions 与
--    render-api/server.js 管理路由直接读写，建库时漏补即报
--    "relation does not exist"。
--
-- 本快照只做「列定义 + 主键」的最小结构，列以最终态为准（依据 server.js
--    查询/写入字段与各迁移 ALTER 结果）。约束、索引、RLS 策略、权限收口
--    仍由后续对应迁移（008/009/015/016/017b/020/021/032/034/039…）负责，
--    避免与本文件重复定义导致命名/语义分叉。
-- ============================================================================

BEGIN;

-- ============ posts ============
CREATE TABLE IF NOT EXISTS public.posts (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name             text,
  media_type            text,
  media_url             text,
  content               text,
  actor_key             text,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz,
  visibility            text DEFAULT 'public',
  is_deleted            boolean NOT NULL DEFAULT false,
  views                 bigint NOT NULL DEFAULT 0,
  is_pinned             boolean NOT NULL DEFAULT false,
  pinned_at             timestamptz,
  -- 帖子定位与 IP 属地（016/017b 引入，全部可空兼容历史数据）
  location_name         text,
  location_province     text,
  location_city         text,
  location_district     text,
  location_level        text,
  ip_province           text,
  ip_city               text,
  ip_region_text        text,
  ip_region_status      text,
  ip_resolved_at        timestamptz,
  ip_lookup_started_at  timestamptz,
  ip_region_error       text
);

-- ============ likes ============
CREATE TABLE IF NOT EXISTS public.likes (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id     bigint,
  user_name   text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ============ comments ============
CREATE TABLE IF NOT EXISTS public.comments (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id           bigint,
  user_name         text,
  content           text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  parent_comment_id bigint,
  generated_by_ai   boolean NOT NULL DEFAULT false
);

-- ============ bans ============
CREATE TABLE IF NOT EXISTS public.bans (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name           text,
  ban_type            text,
  ban_reason          text,
  ban_duration_hours  integer,
  banned_by           text,
  banned_at           timestamptz NOT NULL DEFAULT now(),
  expires_at          timestamptz,
  is_active           boolean NOT NULL DEFAULT true,
  lifted_at           timestamptz,
  lifted_by           text
);

-- ============ blacklist ============
CREATE TABLE IF NOT EXISTS public.blacklist (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name         text,
  reason            text,
  duration_hours    integer,
  added_by          text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  expires_at        timestamptz,
  is_active         boolean NOT NULL DEFAULT true,
  lifted_at         timestamptz,
  lifted_by         text
);

-- ============ mutes ============
CREATE TABLE IF NOT EXISTS public.mutes (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name         text,
  reason            text,
  duration_hours    integer,
  muted_by          text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  expires_at        timestamptz,
  is_active         boolean NOT NULL DEFAULT true,
  lifted_at         timestamptz,
  lifted_by         text
);

COMMIT;
