-- brain_nodes: 个人知识库（记忆/知识/想法）
CREATE TABLE IF NOT EXISTS brain_nodes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT NOT NULL DEFAULT '',
  raw_content TEXT NOT NULL,
  ai_summary TEXT DEFAULT '',
  ai_title TEXT DEFAULT '',
  tags TEXT[] DEFAULT '{}',
  people TEXT[] DEFAULT '{}',
  node_type TEXT DEFAULT 'note',
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','processing','completed','failed')),
  is_public BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_brain_nodes_user ON brain_nodes(user_name);
CREATE INDEX IF NOT EXISTS idx_brain_nodes_status ON brain_nodes(status);
CREATE INDEX IF NOT EXISTS idx_brain_nodes_tags ON brain_nodes USING GIN(tags);
CREATE INDEX IF NOT EXISTS idx_brain_nodes_people ON brain_nodes USING GIN(people);
CREATE INDEX IF NOT EXISTS idx_brain_nodes_created ON brain_nodes(created_at DESC);

-- ai_jobs: 异步 AI 处理队列
CREATE TABLE IF NOT EXISTS ai_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT NOT NULL DEFAULT '',
  job_type TEXT NOT NULL DEFAULT 'organize' CHECK (job_type IN ('organize','deep_think','summarize')),
  ref_table TEXT DEFAULT 'brain_nodes',
  ref_id BIGINT NOT NULL,
  status TEXT DEFAULT 'queued' CHECK (status IN ('queued','running','succeeded','failed')),
  result TEXT DEFAULT '',
  error TEXT DEFAULT '',
  attempts INT DEFAULT 0,
  scheduled_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_jobs_status ON ai_jobs(status);
CREATE INDEX IF NOT EXISTS idx_ai_jobs_scheduled ON ai_jobs(scheduled_at);
