BEGIN;

CREATE SCHEMA IF NOT EXISTS xtj_private;
REVOKE ALL ON SCHEMA xtj_private FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION xtj_private.safe_jsonb(p_value TEXT)
RETURNS JSONB
LANGUAGE plpgsql
IMMUTABLE
STRICT
SET search_path = pg_catalog
AS $$
BEGIN
  RETURN p_value::JSONB;
EXCEPTION WHEN OTHERS THEN
  RETURN '{}'::JSONB;
END;
$$;

REVOKE ALL ON FUNCTION xtj_private.safe_jsonb(TEXT) FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA xtj_private TO service_role;
GRANT EXECUTE ON FUNCTION xtj_private.safe_jsonb(TEXT) TO service_role;

CREATE TABLE IF NOT EXISTS public.storage_cleanup_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  photo_id UUID NOT NULL,
  bucket TEXT NOT NULL DEFAULT 'uploads',
  paths JSONB NOT NULL DEFAULT '[]'::JSONB,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed')),
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  CONSTRAINT storage_cleanup_jobs_photo_unique UNIQUE (photo_id),
  CONSTRAINT storage_cleanup_jobs_paths_array CHECK (jsonb_typeof(paths) = 'array')
);

ALTER TABLE public.storage_cleanup_jobs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.storage_cleanup_jobs FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.storage_cleanup_jobs TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.storage_cleanup_jobs_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.hard_delete_content(
  p_post_id UUID,
  p_actor_user TEXT,
  p_is_admin BOOLEAN,
  p_expect_photo BOOLEAN DEFAULT false,
  p_actor_key TEXT DEFAULT NULL,
  p_storage_paths JSONB DEFAULT '[]'::JSONB
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, xtj_private, pg_temp
AS $$
DECLARE
  v_post public.posts%ROWTYPE;
  v_cleanup_job_id BIGINT;
BEGIN
  IF p_post_id IS NULL OR p_actor_user IS NULL OR btrim(p_actor_user) = '' THEN
    RETURN jsonb_build_object('ok', false, 'code', 'invalid_request', 'error', 'Invalid delete request');
  END IF;

  SELECT * INTO v_post FROM public.posts WHERE id = p_post_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', true, 'deleted', false, 'already_deleted', true);
  END IF;

  IF NOT COALESCE(p_is_admin, false) AND v_post.user_name IS DISTINCT FROM p_actor_user THEN
    RETURN jsonb_build_object('ok', false, 'code', 'forbidden', 'error', 'Not allowed to delete this content');
  END IF;
  IF COALESCE(p_expect_photo, false) AND v_post.media_type IS DISTINCT FROM '__photo_wall__' THEN
    RETURN jsonb_build_object('ok', false, 'code', 'not_photo', 'error', 'Content is not a photo');
  END IF;
  IF NOT COALESCE(p_expect_photo, false) AND v_post.media_type = '__photo_wall__' THEN
    RETURN jsonb_build_object('ok', false, 'code', 'use_photo_delete', 'error', 'Use the photo delete endpoint');
  END IF;

  IF v_post.media_type = '__photo_wall__' AND jsonb_typeof(COALESCE(p_storage_paths, '[]'::JSONB)) = 'array'
     AND jsonb_array_length(COALESCE(p_storage_paths, '[]'::JSONB)) > 0 THEN
    INSERT INTO public.storage_cleanup_jobs (photo_id, paths)
    VALUES (p_post_id, p_storage_paths)
    ON CONFLICT (photo_id) DO UPDATE
      SET paths = EXCLUDED.paths, status = 'pending', updated_at = now(), completed_at = NULL
    RETURNING id INTO v_cleanup_job_id;
  END IF;

  DELETE FROM public.likes WHERE post_id = p_post_id;
  DELETE FROM public.comments WHERE post_id = p_post_id;

  -- Reports contain their notifications in the same JSON record. View events
  -- keep the target UUID in media_url and are removed at the same time.
  DELETE FROM public.posts
  WHERE id <> p_post_id
    AND (
      (media_type = '__post_view__' AND media_url = p_post_id::TEXT)
      OR (media_type = '__report__' AND COALESCE(xtj_private.safe_jsonb(content)->>'target_id', '') = p_post_id::TEXT)
    );

  DELETE FROM public.posts WHERE id = p_post_id;
  IF FOUND THEN
    RETURN jsonb_build_object(
      'ok', true,
      'deleted', true,
      'already_deleted', false,
      'cleanup_job_id', v_cleanup_job_id
    );
  END IF;
  RETURN jsonb_build_object('ok', false, 'code', 'delete_not_applied', 'error', 'Delete did not remove the content');
END;
$$;

REVOKE ALL ON FUNCTION public.hard_delete_content(UUID, TEXT, BOOLEAN, BOOLEAN, TEXT, JSONB) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.hard_delete_content(UUID, TEXT, BOOLEAN, BOOLEAN, TEXT, JSONB) TO service_role;

-- Queue files referenced by historical soft-deleted photos before removing the
-- rows. The backend cleanup worker can safely retry these paths later.
INSERT INTO public.storage_cleanup_jobs (photo_id, paths)
SELECT
  p.id,
  to_jsonb(array_remove(ARRAY[
    NULLIF(xtj_private.safe_jsonb(p.content)->>'storagePath', ''),
    NULLIF(xtj_private.safe_jsonb(p.content)->>'thumb', ''),
    NULLIF(split_part(substring(COALESCE(p.media_url, '') from '/uploads/(.*)$'), '?', 1), ''),
    NULLIF(regexp_replace(split_part(substring(COALESCE(p.media_url, '') from '/uploads/(.*)$'), '?', 1), '(\.[^.]+)$', '_thumb\1'), '')
  ]::TEXT[], NULL))
FROM public.posts p
WHERE p.media_type = '__photo_wall__'
  AND p.is_deleted IS TRUE
ON CONFLICT (photo_id) DO NOTHING;

DELETE FROM public.likes
WHERE post_id IN (SELECT id FROM public.posts WHERE media_type = '__photo_wall__' AND is_deleted IS TRUE);
DELETE FROM public.comments
WHERE post_id IN (SELECT id FROM public.posts WHERE media_type = '__photo_wall__' AND is_deleted IS TRUE);
DELETE FROM public.posts WHERE media_type = '__photo_wall__' AND is_deleted IS TRUE;

-- Pro/VIP is permanently retired. Remove callable claim surfaces first, then
-- purge the historical marker rows without touching normal posts or themes.
DROP FUNCTION IF EXISTS public.claim_pro_gift(TEXT, TEXT);
DROP FUNCTION IF EXISTS public.claim_pro_gift(TEXT, TEXT, TEXT, TEXT, TEXT);
DROP FUNCTION IF EXISTS public.claim_pro_gift_for_user(TEXT, UUID);
DROP INDEX IF EXISTS public.idx_claims_uniq;

DELETE FROM public.likes
WHERE post_id IN (
  SELECT id FROM public.posts
  WHERE media_type IN ('__vip__', '__vip_order__', '__vip_plan__', '__pro_gift__', '__pro_gift_claim__', '__user_style__')
);
DELETE FROM public.comments
WHERE post_id IN (
  SELECT id FROM public.posts
  WHERE media_type IN ('__vip__', '__vip_order__', '__vip_plan__', '__pro_gift__', '__pro_gift_claim__', '__user_style__')
);
DELETE FROM public.posts
WHERE media_type IN ('__vip__', '__vip_order__', '__vip_plan__', '__pro_gift__', '__pro_gift_claim__', '__user_style__');

COMMIT;
