-- Harden post-028 stream ownership and repair photo cleanup/view helpers.

CREATE OR REPLACE FUNCTION public.increment_post_views(p_post_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_views INTEGER;
BEGIN
  UPDATE public.posts
     SET views = COALESCE(views, 0) + 1
   WHERE id = p_post_id
     AND media_type = '__photo_wall__'
  RETURNING views INTO v_views;
  RETURN COALESCE(v_views, 0);
END;
$$;

REVOKE ALL ON FUNCTION public.increment_post_views(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.increment_post_views(UUID) TO anon, authenticated, service_role;

-- The application has used both username and UUID values in user_id over time.
-- Match either representation so a username claim cannot hide UUID-owned rows
-- (and vice versa).
DROP POLICY IF EXISTS "Users can view own stream sessions" ON public.ai_stream_sessions;
CREATE POLICY "Users can view own stream sessions"
  ON public.ai_stream_sessions
  FOR SELECT TO authenticated
  USING (
    user_id = auth.uid()::text
    OR user_id = NULLIF(auth.jwt() ->> 'user_name', '')
    OR user_id = NULLIF(auth.jwt() ->> 'username', '')
    OR user_id = NULLIF(auth.jwt() -> 'app_metadata' ->> 'user_name', '')
    OR user_id = NULLIF(auth.jwt() -> 'app_metadata' ->> 'username', '')
  );

DROP POLICY IF EXISTS "Users can view own stream events" ON public.ai_stream_events;
CREATE POLICY "Users can view own stream events"
  ON public.ai_stream_events
  FOR SELECT TO authenticated
  USING (
    user_id = auth.uid()::text
    OR user_id = NULLIF(auth.jwt() ->> 'user_name', '')
    OR user_id = NULLIF(auth.jwt() ->> 'username', '')
    OR user_id = NULLIF(auth.jwt() -> 'app_metadata' ->> 'user_name', '')
    OR user_id = NULLIF(auth.jwt() -> 'app_metadata' ->> 'username', '')
  );

-- Migration 013 used the legacy *_thumb naming convention. Add the actual
-- thumbnail path generated by render-api/photo-create.js to pending jobs.
WITH photo_paths AS (
  SELECT p.id,
         split_part(substring(COALESCE(p.media_url, '') from '/uploads/(.*)$'), '?', 1) AS storage_path
    FROM public.posts p
   WHERE p.media_type = '__photo_wall__' AND p.is_deleted IS TRUE
), repaired AS (
  SELECT j.id,
         jsonb_agg(to_jsonb(path) ORDER BY path) AS paths
    FROM public.storage_cleanup_jobs j
    JOIN photo_paths p ON p.id = j.photo_id
    CROSS JOIN LATERAL (
      SELECT value AS path FROM jsonb_array_elements_text(COALESCE(j.paths, '[]'::jsonb))
      UNION
      SELECT 'photos/thumbs/' || encode(digest(p.storage_path, 'sha256'), 'hex') || '.webp'
       WHERE p.storage_path <> ''
    ) candidates
   WHERE candidates.path <> ''
   GROUP BY j.id
)
UPDATE public.storage_cleanup_jobs j
   SET paths = repaired.paths,
       updated_at = now()
  FROM repaired
 WHERE j.id = repaired.id;
